import React, { useCallback, useContext, useRef, useState } from 'react';
import { View, Text, SafeAreaView, TouchableOpacity, Alert, ScrollView } from 'react-native';
import NavigationButtons from '@/components/onboarding/NavigationButtons';
import CheckInHeader from '@/components/onboarding/CheckInHeader';
import { OnboardingV2ScreenProps } from '../../types';
import { beforeToday, formatDay } from '@/utils/date/helpers';
import { DiaryDataContext } from '@/context/diaryData';
import { INDICATEURS_HUMEUR } from '@/utils/liste_indicateurs.1';
import { TW_COLORS } from '@/utils/constants';
import BannerHeader from '../../BannerHeader';
import { useAnimatedStyle } from 'react-native-reanimated';
import { moodBackgroundColors, moodEmojis } from '@/utils/mood';
import InstructionText from '../../InstructionText';
import { firstLetterUppercase } from '@/utils/string-util';
import { colors } from '@/utils/colors';
import CheckMarkIcon from '@assets/svg/icon/check'
import PlusIcon from '@assets/svg/icon/plus'
import { SafeAreaViewWithOptionalHeader } from '@/scenes/onboarding/ProgressHeader';
import { BottomSheetBackdrop, BottomSheetModal, BottomSheetView } from '@gorhom/bottom-sheet';
import HelpText from '@/components/HelpText';
import HelpView from '@/components/HelpView';
import { HELP_FOR_CATEGORY } from '@/scenes/onboarding-v2/data/helperData';
import { INDICATORS_CATEGORIES } from '@/entities/Indicator';
import { useBottomSheet } from '@/context/BottomSheetContext';
import { mergeClassNames } from '@/utils/className';
import { typography } from '@/utils/typography';
import { useFocusEffect } from '@react-navigation/native';
import { useStatusBar } from '@/context/StatusBarContext';


type Props = OnboardingV2ScreenProps<'OnboardingCheckInHowDoYouFeelDetails'>;

// @todo this value where generated by chatgpt, see if this is the value we want to set
const SadMoodOptions = [
  'colère', 'anxiété', 'peur', 'accablement', 'honte',
  'dégoût', 'embarras', 'frustration', 'contrariété',
  'jalousie', 'angoisse', 'comportement'
];

const HappyMoodOptions = [
  'enthousiasme',
  'fierté',
  'amour',
  'espoir',
  'sérénité',
  'soulagement',
  'amusement',
  'fascination',
  'gratitude',
  'admiration',
  'exaltation',
  'euphorie',
  'plaisir',
  'contentement',
  'satisfaction',
  'optimisme',
  'tendresse'
]

const NeutralMoodOptions = [
  'curiosité',
  'surprise',
  'intérêt',
  'attente',
  'indifférence',
  'calme',
  'neutralité',
  'acceptation',
  'concentration',
  'réflexion',
  'méditation',
  'observateur',
  'prudence',
  'détachement',
  'tolérance',
  'équanimité'
]

const getMoodOptions = (mood: number): string[] => {
  if (mood < 2) {
    return SadMoodOptions
  } else if (mood > 2) {
    return HappyMoodOptions
  } else {
    return NeutralMoodOptions
  }
}

export const OnboardingCheckInLastMoods: React.FC<Props> = ({ navigation, route }) => {
  const [selectedMoods, setSelectedMoods] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const moodOptions = React.useMemo(() => getMoodOptions(route.params?.mood), [route.params?.mood])
  const [diaryData, addNewEntryToDiaryData] = useContext(DiaryDataContext);
  const { showBottomSheet } = useBottomSheet();
  const { setCustomColor } = useStatusBar();

  useFocusEffect(
    useCallback(() => {
      if (route.params?.mood !== null) {
        setTimeout(() => {
          setCustomColor(moodBackgroundColors[route.params?.mood]);
        }, 0)
      }

      return () => {
        // Optional cleanup here
      };
    }, [route.params?.mood])
  );

  const showHelpModal = () => {
    return showBottomSheet(<HelpView
      title={HELP_FOR_CATEGORY[INDICATORS_CATEGORIES["Emotions/sentiments"]].title}
      description={HELP_FOR_CATEGORY[INDICATORS_CATEGORIES["Emotions/sentiments"]]?.description} />)
  }

  const toggleMood = (mood: string) => {
    setSelectedMoods(prev => {
      if (prev.includes(mood)) {
        return prev.filter(m => m !== mood);
      } else {
        return [...prev, mood];
      }
    });
  };

  const handleComplete = async () => {
    setLoading(true);
    try {
      const date = formatDay(beforeToday(0))
      const prev = diaryData[date] || {}
      const key = INDICATEURS_HUMEUR.name
      const updatedAnswers = {
        ...prev,
        [key]: {
          ...prev[key],
          // duplicating the information in userComments and moods for the time being
          userComment: selectedMoods.join(', '),
          moods: selectedMoods
        },
      }
      addNewEntryToDiaryData({
        date,
        answers: updatedAnswers
      });

      navigation.navigate('OnboardingCheckInMoodSummary', {
        mood: route.params?.mood,
        selectedMoods: selectedMoods,
      })
      console.log(route.params?.mood, 'route.params?.mood')
    } catch (error) {
      console.error('Error completing onboarding:', error);
      Alert.alert('Erreur', 'Une erreur est survenue. Veuillez réessayer.');
    } finally {
      setLoading(false);
    }
  };

  const handlePrevious = () => {
    navigation.goBack();
  };

  const renderMoodSelector = () => (
    <View className="mb-6 mt-6">
      <View className="flex-row flex-wrap gap-x-3 gap-y-3">
        {moodOptions.map((mood, index) => {
          const isSelected = selectedMoods.includes(mood);
          return (
            <TouchableOpacity
              key={index}
              onPress={() => toggleMood(mood)}
              className="px-4 py-2 rounded-lg"
              style={{
                borderWidth: 2,
                position: 'relative',
                borderColor: 'transparent',
              }}
            >
              <View className="flex-row items-center justify-center">
                <Text
                  className={mergeClassNames(typography.textSmSemibold, 'text-brand-900 mr-1')}
                >
                  {firstLetterUppercase(mood)}
                </Text>
                {isSelected ? <CheckMarkIcon /> : <PlusIcon />}
              </View>
              <View style={{
                position: 'absolute',
                top: 0,
                bottom: 0,
                left: 0,
                right: 0,
                borderWidth: isSelected ? 2 : 1,
                backgroundColor: isSelected ? colors.LIGHT_BLUE_TRANS_02 : TW_COLORS.WHITE,
                borderColor: TW_COLORS.PRIMARY,
                borderRadius: 8, // match rounded-lg
                zIndex: -1, // optional if you want it behind content
              }}></View>
            </TouchableOpacity>
          );
        })}
      </View>
    </View>
  );

  const animatedStatusBarColor = useAnimatedStyle(() => {
    return {
      backgroundColor: route.params?.mood !== null ? moodBackgroundColors[route.params?.mood] : TW_COLORS.WHITE,
    };
  })

  const animatedTextColor = useAnimatedStyle(() => {
    return {
      backgroundColor: 'transparent',
      color: TW_COLORS.PRIMARY
    };
  })

  const bottomSheetRef = useRef<BottomSheetModal>(null);

  const handleSheetChanges = useCallback((index: number) => {
    console.log('handleSheetChanges', index);
  }, []);

  const renderBackdrop = useCallback(
    props => (<BottomSheetBackdrop {...props}
      opacity={0.5}
      enableTouchThrough={false}
      appearsOnIndex={0}
      disappearsOnIndex={-1}
      style={[{ backgroundColor: 'rgba(0, 0, 0, 1)' }]} />),
    []
  );

  return (
    <SafeAreaViewWithOptionalHeader className="flex-1 bg-white">
      <BannerHeader
        animatedStatusBarColor={animatedStatusBarColor}
        animatedTextColor={animatedTextColor}
        headerTitle='Observation du jour'
        title={`Y-a-t-il une émotion, un état ou un comportement qui a pris un peu de place aujourd'hui ?`}
        leftAction={showHelpModal}
        leftComponent={<HelpText />}
      // handlePrevious={handlePrevious}
      // handleSkip={handleSkip}
      >
        {route.params?.mood !== null && <View className='justify-center items-center mt-4'>
          {moodEmojis[route.params?.mood]?.icon}
        </View>}
      </BannerHeader>
      <ScrollView className="flex-1 p-6" contentContainerStyle={{ paddingBottom: 100 }}>
        <InstructionText>
          Sélectionnez votre ressenti du moment
        </InstructionText>
        {renderMoodSelector()}
      </ScrollView>
      <NavigationButtons
        onNext={handleComplete}
        absolute={true}
        // showPrevious={false}
        onPrevious={handlePrevious}
        loading={loading}
        nextText="Renseigner mes émotions"
      />
    </SafeAreaViewWithOptionalHeader>
  );
};

export default OnboardingCheckInLastMoods;
