import { OnboardingStep } from './types';

export const ONBOARDING_V2_STEPS: Record<OnboardingStep, OnboardingStep> = {
  INTRO: 'INTRO',
  PROFILE: 'PROFILE',
  CAROUSEL: 'CAROUSEL',
  DIFFICULTIES: 'DIFFICULTIES',
  OBJECTIVE: 'OBJECTIVE',
  CHECKIN: 'CHECKIN',
};

export const STEP_ORDER: OnboardingStep[] = [
  'INTRO',
  'PROFILE', 
  'CAROUSEL',
  'DIFFICULTIES',
  'OBJECTIVE',
  'CHECKIN',
];

export const STEP_PROGRESS: Record<OnboardingStep, number> = {
  INTRO: 1,
  PROFILE: 2,
  CAROUSEL: 3,
  DIFFICULTIES: 4,
  OBJECTIVE: 5,
  CHECKIN: 6,
};

export const TOTAL_STEPS = STEP_ORDER.length;

// Storage keys
export const STORAGE_KEYS = {
  ONBOARDING_V2_STATE: '@ONBOARDING_V2_STATE',
  ONBOARDING_V2_PROFILE: '@ONBOARDING_V2_PROFILE',
  ONBOARDING_V2_DIFFICULTIES: '@ONBOARDING_V2_DIFFICULTIES',
  ONBOARDING_V2_OBJECTIVE: '@ONBOARDING_V2_OBJECTIVE',
  ONBOARDING_V2_CHECKIN: '@ONBOARDING_V2_CHECKIN',
  ONBOARDING_V2_COMPLETED: '@ONBOARDING_V2_COMPLETED',
};

// Colors
export const COLORS = {
  PRIMARY: '#1FC6D5',
  SECONDARY: '#00CEF7',
  SUCCESS: '#4CAF50',
  WARNING: '#FF9800',
  ERROR: '#F44336',
  BACKGROUND: '#F5F5F5',
  WHITE: '#FFFFFF',
  BLACK: '#000000',
  GRAY_LIGHT: '#E0E0E0',
  GRAY_MEDIUM: '#9E9E9E',
  GRAY_DARK: '#424242',
  TEXT_PRIMARY: '#212121',
  TEXT_SECONDARY: '#757575',
};
