import { ToolItemType, ToolItemEntity, ToolItemTheme, ToolItemAudience } from "../../entities/ToolItem";

// Re-export types for backward compatibility
export type { ToolItemType, ToolItemEntity, ToolItemTheme, ToolItemAudience };

export const TOOLS_DATA: ToolItemEntity[] = [
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    title: "Agenda du sommeil",
    description:
      "Cet agenda permet de suivre vos habitudes de sommeil au quotidien : heures de coucher, réveils, qualité du sommeil et comportements liés à la vigilance. Il aide à mieux comprendre vos rythmes et à identifier d'éventuels troubles du sommeil.",
    type: ["Fichier"],
    themes: ["Améliorer son sommeil"],
    audience: ["Pour tous"],
    url: "https://www.reseau-morphee.fr/wp-content/uploads/2009/01/agenda_2p.pdf",
    source: "Reseau Morphée",
  },
  {
    id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
    title: "Identifier le professionnel de santé adapté",
    description:
      "PRIMO est un questionnaire d'auto-évaluation pour les jeunes. Il aide à identifier des signes de souffrance psychique, à mieux comprendre vos émotions et à être orienté vers des ressources ou professionnels adaptés.",
    type: ["Questionnaire"],
    themes: ["Apprendre à se connaître", "Reconnaître ses besoins", "Reconnaître ses émotions", "Trouver de l'aide"],
    audience: ["Jeunes"],
    url: "https://primo.santepsyjeunes.fr/0",
    source: "Sante Psy Jeunes",
  },
  {
    id: "c3d4e5f6-a7b8-9012-cdef-123456789012",
    title: "Évaluez la gravité d'une addiction",
    description:
      "Ce test permet d'évaluer la gravité d'une addiction - qu'elle soit liée à une substance ou à un comportement - selon quatre niveaux : absente, légère, modérée ou sévère.",
    type: ["Questionnaire"],
    themes: ["Agir sur mes addictions", "Apprendre à se connaître", "Trouver de l'aide"],
    audience: ["Pour tous"],
    url: "https://www.addictaide.fr/parcours/gravite/",
    source: "Addict'AIDE",
  },
  {
    id: "d4e5f6a7-b8c9-0123-def1-234567890123",
    title: "Repérez les usages nocifs de substances psychoactives chez les adolescents et jeunes adultes (Test ADOSPA)",
    description:
      "Le test ADOSPA est un questionnaire pour dépister précocement les usages à risque ou nocifs d'alcool et de drogues chez les jeunes. Il comporte 6 questions, et un score supérieur à 3 indique un risque élevé.",
    type: ["Questionnaire"],
    themes: ["Agir sur mes addictions", "Apprendre à se connaître", "Trouver de l'aide"],
    audience: ["Jeunes", "Parents"],
    url: "https://www.addictaide.fr/parcours/craft/",
    source: "Addict'AIDE",
  },
  {
    id: "e5f6a7b8-c9d0-1234-ef12-345678901234",
    title: "Évaluez votre niveau de dépendance aux jeux d'argent et de hasard (Test ICJE)",
    description:
      "Ce questionnaire évalue votre dépendance aux jeux d'argent et de hasard via 9 questions. Il permet de mesurer le risque et d'identifier un usage problématique.",
    type: ["Questionnaire"],
    themes: ["Agir sur mes addictions", "Apprendre à se connaître", "Trouver de l'aide"],
    audience: ["Pour tous"],
    url: "https://www.addictaide.fr/parcours/icje/",
    source: "Addict'AIDE",
  },
  {
    id: "f6a7b8c9-d0e1-2345-f123-456789012345",
    title: "Évaluez votre usage d'internet (Internet - Test IAT)",
    description:
      "Ce test (Internet Addiction Test – IAT) vous permet d'évaluer si votre usage d'internet est excessif : 20 questions pour mesurer la dépendance et ses impacts sur votre vie quotidienne.",
    type: ["Questionnaire"],
    themes: ["Agir sur mes addictions", "Apprendre à se connaître", "Trouver de l'aide"],
    audience: ["Pour tous"],
    url: "https://www.addictaide.fr/parcours/internet/",
    source: "Addict'AIDE",
  },
  {
    id: "a7b8c9d0-e1f2-3456-1234-567890123456",
    title: "Mesurez votre dépendance aux jeux vidéo (Game Addiction Scale)",
    description:
      "Ce questionnaire GAS (Game Addiction Scale) vous permet d'évaluer votre dépendance aux jeux vidéo à travers 7 questions sur vos habitudes de jeu au cours des 6 derniers mois.",
    type: ["Questionnaire"],
    themes: ["Agir sur mes addictions", "Apprendre à se connaître", "Trouver de l'aide"],
    audience: ["Pour tous"],
    url: "https://www.addictaide.fr/parcours/gas/",
    source: "Addict'AIDE",
  },
  {
    id: "b8c9d0e1-f2a3-4567-2345-678901234567",
    title: "Mesurez votre consommation de cannabis (Questionnaire CAST)",
    description:
      "Ce questionnaire mesure votre consommation de cannabis avec le test CAST (Cannabis Abuse Screening Test) : 6 questions pour identifier un usage potentiellement problématique.",
    type: ["Questionnaire"],
    themes: ["Agir sur mes addictions", "Apprendre à se connaître", "Trouver de l'aide"],
    audience: ["Pour tous"],
    url: "https://www.addictaide.fr/parcours/cast/",
    source: "Addict'AIDE",
  },
  {
    id: "c9d0e1f2-a3b4-5678-3456-789012345678",
    title: "Évaluez un usage nocif de cannabis (Test ALAC)",
    description:
      "Ce questionnaire ALAC vous permet d'évaluer votre consommation de cannabis et d'identifier un usage potentiellement nocif. Il s'agit d'un auto-test simple et rapide pour prendre conscience de votre rapport à cette substance.",
    type: ["Questionnaire"],
    themes: ["Agir sur mes addictions", "Apprendre à se connaître", "Trouver de l'aide"],
    audience: ["Pour tous"],
    url: "https://www.addictaide.fr/parcours/alac/",
    source: "Addict'AIDE",
  },
  {
    id: "d0e1f2a3-b4c5-6789-4567-890123456789",
    title: "Mesurez vos chances de réussite du sevrage tabagique (Test Demaria-Grimaldi-Lagrue)",
    description:
      "Ce questionnaire (Test de Demaria-Grimaldi-Lagrue) mesure vos chances de réussite à arrêter de fumer. Il se compose de 17 questions (oui/non) et vous aide à évaluer votre motivation et le bon moment pour entreprendre un sevrage tabagique.",
    type: ["Questionnaire"],
    themes: ["Agir sur mes addictions", "Apprendre à se connaître", "Trouver de l'aide"],
    audience: ["Pour tous"],
    url: "https://www.addictaide.fr/parcours/demaria/",
    source: "Addict'AIDE",
  },
  {
    id: "e1f2a3b4-c5d6-7890-5678-901234567890",
    title: "Évaluez votre motivation à arrêter de fumer (Test de Lagrue et Légeron)",
    description:
      "Ce test calcule votre niveau de motivation à arrêter de fumer. Il se base sur 4 questions développées par Lagrue et Légeron : un score élevé signifie une motivation forte, un score faible indique que vous êtes moins prêt à quitter le tabac.",
    type: ["Questionnaire"],
    themes: ["Agir sur mes addictions", "Apprendre à se connaître", "Trouver de l'aide"],
    audience: ["Pour tous"],
    url: "https://www.addictaide.fr/parcours/lagrue/",
    source: "Addict'AIDE",
  },
  {
    id: "f2a3b4c5-d6e7-8901-6789-012345678901",
    title: "Quantifiez votre niveau de dépendance au tabac (Test de Fagerström)",
    description:
      "Ce questionnaire mesure votre niveau de dépendance au tabac. Basé sur le test de Fagerström, il calcule un score (de 0 à 10) qui indique si votre dépendance est faible, moyenne ou forte.",
    type: ["Questionnaire"],
    themes: ["Agir sur mes addictions", "Apprendre à se connaître", "Trouver de l'aide"],
    audience: ["Pour tous"],
    url: "https://www.addictaide.fr/parcours/fagerstrom/",
    source: "Addict'AIDE",
  },
  {
    id: "a3b4c5d6-e7f8-9012-7890-123456789012",
    title: "Évaluez votre risque d'addiction à l'alcool (Questionnaire AUDIT)",
    description:
      "Ce questionnaire AUDIT vous permet d'évaluer votre consommation d'alcool et les risques associés. Il est basé sur 10 questions validées par l'OMS et aide à mieux comprendre votre relation avec l'alcool.",
    type: ["Questionnaire"],
    themes: ["Agir sur mes addictions", "Apprendre à se connaître", "Trouver de l'aide"],
    audience: ["Pour tous"],
    url: "https://www.addictaide.fr/parcours/audit/",
    source: "Addict'AIDE",
  },
  {
    id: "b4c5d6e7-f8a9-0123-9012-345678901234",
    title: "S'ancrer dans le présent - 6 min",
    description:
      "Pendant six minutes, cet exercice vous aide à vous ancrer dans le moment présent : observer vos pensées et émotions sans vous laisser emporter, et prêter attention à ce que vous êtes en train de faire.",
    type: ["Audio", "Exercice"],
    themes: ["Diminuer le stress", "Gérer les pensées difficiles", "Reconnaître ses émotions", "Réguler ses émotions", "Se relaxer"],
    audience: ["Pour tous"],
    url: "https://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Grounding_Exercise_1__5_minutes_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "c5d6e7f8-a9b0-1234-9012-345678901234",
    title: "Réseau des centres du sommeil",
    description:
      "Cette page liste les centres du sommeil agréés en France pour diagnostiquer et traiter les troubles du sommeil. Elle propose une cartographie des structures, ainsi que les coordonnées des centres spécialisés dans chaque région.",
    type: ["Carte"],
    themes: ["Améliorer son sommeil", "Trouver de l'aide"],
    audience: ["Pour tous"],
    url: "https://institut-sommeil-vigilance.org/ou-consulter-reseau-sommeil-france/",
    source: "INSV",
  },
  {
    id: "d6e7f8a9-b0c1-2345-0123-456789012345",
    title: "Poser ses maux",
    description:
      "Cet outil vous permet d'écrire ce que vous ressentez quand le mal-être est flou : un mini-jeu vous aide à choisir des mots qui correspondent à votre ressenti, puis à les transformer en un message. Vous pouvez conserver ce texte ou l'envoyer à une personne de confiance.",
    type: ["Jeu"],
    themes: ["Apprendre à se connaître", "Gérer les pensées difficiles", "Reconnaître ses émotions"],
    audience: ["Pour tous"],
    url: "https://www.nightline.fr/kit-de-vie/poser-ses-maux",
    source: "Nightline",
  },
  {
    id: "e7f8a9b0-c1d2-3456-1234-567890123456",
    title: "Body Scan",
    description:
      "Cette vidéo propose un body scan, un exercice de pleine conscience consistant à porter votre attention sur différentes parties de votre corps, de la tête aux pieds. Il permet de relâcher les tensions, d'améliorer la conscience corporelle et de favoriser un état de calme et de détente.",
    type: ["Vidéo"],
    themes: ["Diminuer le stress", "Se relaxer"],
    audience: ["Pour tous"],
    url: "https://www.youtube.com/watch?v=D89hIkSRvnY",
    source: "Nightline",
  },
  {
    id: "f8a9b0c1-d2e3-4567-2345-678901234567",
    title: "Crise de calme",
    description:
      "Si vous trouvez la méditation difficile, vous pouvez essayer la crise de calme : une vidéo courte de 3 minutes qui vous aide à retrouver rapidement calme et apaisement.",
    type: ["Vidéo"],
    themes: ["Diminuer le stress", "Se relaxer"],
    audience: ["Pour tous"],
    url: "https://www.youtube.com/watch?v=9VUp582KRH8",
    source: "Nightline",
  },
  {
    id: "c5d6e7f8-a9b0-1234-0123-456789012345",
    title: `Maintenir son attention sur le présent : Exercice "Conscience de boire"`,
    description:
      "Pendant huit minutes, cet exercice vous aide à vous ancrer dans le moment présent : observer vos pensées et émotions sans vous laisser emporter, et prêter attention à ce que vous êtes en train de faire.",
    type: ["Audio", "Exercice"],
    themes: ["Diminuer le stress", "Gérer les pensées difficiles", "Reconnaître ses émotions", "Réguler ses émotions", "Se relaxer"],
    audience: ["Pour tous"],
    url: "https://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Awareness_of_Drinking_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "b0c1d2e3-f4a5-6789-4567-890123456789",
    title: "Agir sur mes comportements",
    description:
      "Cet outil vous aide à identifier des activités positives et à les intégrer dans votre quotidien. Il propose des stratégies simples pour agir sur vos comportements, rester motivé et renforcer votre bien-être, même dans les moments difficiles.",
    type: ["Article", "Jeu"],
    themes: ["Bienveillance envers soi-même", "Gérer les pensées difficiles", "Vie quotidienne"],
    audience: ["Pour tous"],
    url: "https://www.nightline.fr/kit-de-vie/agir-sur-mes-comportements",
    source: "Nightline",
  },
  {
    id: "c1d2e3f4-a5b6-7890-5678-901234567890",
    title: "MyClepsy",
    description:
      "CléPsy est un site conçu pour accompagner les parents au quotidien dans leur parentalité et la santé mentale de leurs enfants. Il propose aussi un assistant virtuel de guidance parentale accessible via Whatsapp.",
    type: ["Chatbot"],
    themes: ["Trouver de l'aide", "Vie quotidienne"],
    audience: ["Parents"],
    url: "https://www.clepsy.fr/",
    source: "CléPsy",
  },
  {
    id: "d2e3f4a5-b6c7-8901-6789-012345678901",
    title: "Plan personnel de gestion de crise",
    description:
      "Ce livret vous aide à préparer un plan de gestion de crise : repérer vos signes d'alerte, identifier ce qui peut vous apaiser, et noter les personnes ou services à contacter si vous traversez une situation très difficile.",
    type: ["Fichier"],
    themes: ["Gérer les pensées difficiles", "Gérer une crise"],
    audience: ["Pour tous"],
    url: "https://ateliers-rehab.ch/docs/revim/REVIM_Mon-plan-de-gestion-de-crise-2025.pdf",
    source: "Centre Ressources de Réhabilitation Psychosociale",
  },
  {
    id: "e3f4a5b6-c7d8-9012-7890-123456789012",
    title: "Les livrets d'auto-soin du CCR",
    description:
      "Ces livrets d'auto-soin proposent des exercices pratiques pour mieux gérer vos émotions, vos pensées, votre sommeil et vos activités quotidiennes. Ils aident aussi à réfléchir sur soi et à renforcer votre bien-être, à votre rythme, que vous viviez ou non un trouble psychique.",
    type: ["Fichier"],
    themes: [
      "Améliorer son sommeil",
      "Apprendre à se connaître",
      "Bienveillance envers soi-même",
      "Diminuer le stress",
      "Gérer les pensées difficiles",
      "Gérer une crise",
      "Reconnaître ses besoins",
      "Reconnaître ses émotions",
      "Respecter ses limites",
      "Vie quotidienne",
    ],
    audience: ["Pour tous"],
    url: "https://centre-ressource-rehabilitation.org/outil-livrets-d-auto-soin",
    source: "Centre Ressources de Réhabilitation Psychosociale",
  },
  {
    id: "f4a5b6c7-d8e9-0123-8901-234567890123",
    title: "Les activités individuelles créatives de l'Etonnant Periple",
    description:
      "Ce cahier propose des activités positives co-construits avec des personnes concernées par des troubles psychiques. Il est conçu pour favoriser l'affirmation de soi, la connaissance de soi et le bien-être.",
    type: ["Fichier"],
    themes: ["Apprendre à se connaître", "Bienveillance envers soi-même"],
    audience: ["Pour tous"],
    url: "https://etonnant-periple.fr/activites-individuelles/",
    source: "Etonnant Périple",
  },
  {
    id: "a5b6c7d8-e9f0-1234-9012-345678901234",
    title: "Hop Ma Liste",
    description:
      "Cette application vous aide à traverser les moments de crise : identifier vos signes d'alerte, activer vos stratégies de soutien, et accéder à des ressources et messages positifs pour vous calmer et vous protéger.",
    type: ["App"],
    themes: ["Gérer les pensées difficiles", "Gérer une crise"],
    audience: ["Pour tous"],
    url: "https://www.chu-angers.fr/offre-de-soins/acteur-de-sante-publique/hop-ma-liste-134448.kjsp",
    source: "CHU Angers",
  },
  {
    id: "b6c7d8e9-f0a1-2345-0123-456789012345",
    title: "Respirelax",
    description:
      "Cette application propose des exercices guidés de cohérence cardiaque pour calmer le corps et l'esprit. Elle aide à réduire le stress, favoriser la détente et propose des séances adaptables à votre niveau, disponibles hors-ligne.",
    type: ["App"],
    themes: ["Diminuer le stress", "Réguler ses émotions", "Se relaxer", "Vie quotidienne"],
    audience: ["Pour tous"],
    url: "https://www.thermes-allevard.com/content/respirelax-0",
    source: "Thermes Allevard",
  },
  {
    id: "c7d8e9f0-a1b2-3456-1234-567890123456",
    title: "Carte des lieux pour trouver de l'aide",
    description:
      "Ce site répertorie des ressources fiables pour trouver de l'aide en santé mentale : professionnels (psychiatres, psychologues), associations, numéros d'écoute et dispositifs publics. Il vous guide vers des solutions adaptées selon votre situation.",
    type: ["Carte"],
    themes: ["Aider un proche", "Trouver de l'aide"],
    audience: ["Pour tous"],
    url: "https://www.sante.fr/sante-mentale-2/ou-trouver-de-laide",
    source: "Santé.fr",
  },
  {
    id: "d8e9f0a1-b2c3-4567-2345-678901234567",
    title: "Se former au secourisme en santé mentale",
    description:
      "PSSM Formation propose des formations aux « Premiers Secours en Santé Mentale » pour : apprendre à reconnaître les signes de détresse psychique, écouter sans jugement, soutenir une personne en crise et l'orienter vers de l'aide.",
    type: ["Formation"],
    themes: ["Aider un proche", "Se former"],
    audience: ["Pour tous"],
    url: "https://www.pssmformation.fr/",
    source: "PSSM",
  },
  {
    id: "e9f0a1b2-c3d4-5678-3456-789012345678",
    title: "Consommation d'alcool : Questionnaire FACE",
    description:
      "Le questionnaire FACE (fast alcohol consumption evaluation) vous permet d'autoévaluer vos habitudes de consommation d'alcool de façon anonyme et guidée.",
    type: ["Questionnaire"],
    themes: ["Agir sur mes addictions", "Apprendre à se connaître", "Trouver de l'aide"],
    audience: ["Pour tous"],
    url: "https://www.addictaide.fr/parcours/face/?quest=true#/face",
    source: "Addict'AIDE",
  },
  {
    id: "f0a1b2c3-d4e5-6789-4567-890123456789",
    title: "Relaxation musculaire",
    description:
      "Cet exercice audio vous guide pour détendre vos muscles en les contractant puis en les relâchant progressivement. Il permet de relâcher les tensions et de favoriser un état de calme et de détente.",
    type: ["Audio", "Exercice"],
    themes: ["Diminuer le stress", "Réguler ses émotions", "Se relaxer"],
    audience: ["Pour tous"],
    url: "https://www.santementale-info-service.fr/en-prendre-soin/tous-les-exercices/relaxation-musculaire",
    source: "Santé Mentale Info Service",
  },
  {
    id: "a1b2c3d4-e5f6-7890-5678-901234567890",
    title: "Cohérence cardiaque",
    description:
      "Cet exercice vidéo vous guide dans une respiration rythmée : inspirez lorsque la bulle monte, expirez lorsqu'elle descend. Pratiqué assis et détendu, il permet de calmer le corps et l'esprit, de réduire le stress et de retrouver rapidement une sensation d'apaisement.",
    type: ["Vidéo", "Exercice"],
    themes: ["Diminuer le stress", "Réguler ses émotions", "Se relaxer"],
    audience: ["Pour tous"],
    url: "https://www.santementale-info-service.fr/en-prendre-soin/tous-les-exercices/coherence-cardiaque",
    source: "Santé Mentale Info Service",
  },
  {
    id: "b2c3d4e5-f6a7-8901-6789-012345678901",
    title: "Journal du sommeil",
    description:
      "Cette fiche PDF vous invite à suivre votre sommeil jour après jour. Elle permet d'identifier vos habitudes, de repérer les facteurs qui perturbent votre sommeil, et de mieux comprendre comment améliorer vos nuits.",
    type: ["Observation", "Fichier", "Exercice"],
    themes: ["Améliorer son sommeil", "Vie quotidienne"],
    audience: ["Pour tous"],
    url: "https://www.santementale-info-service.fr/en-prendre-soin/tous-les-exercices/mon-journal-du-sommeil",
    source: "Santé Mentale Info Service",
  },
  {
    id: "c3d4e5f6-a7b8-9012-7890-123456789012",
    title: "Journal de gratitude",
    description:
      "Cette fiche PDF consiste à tenir un journal de gratitude, en notant régulièrement les moments positifs, les personnes ou les événements pour lesquels vous vous sentez reconnaissant.",
    type: ["Observation", "Fichier", "Exercice"],
    themes: ["Bienveillance envers soi-même", "Reconnaître ses émotions", "Se relaxer", "Vie quotidienne"],
    audience: ["Pour tous"],
    url: "https://www.santementale-info-service.fr/en-prendre-soin/tous-les-exercices/mon-journal-de-gratitude",
    source: "Santé Mentale Info Service",
  },
  {
    id: "d4e5f6a7-b8c9-0123-8901-234567890123",
    title: "Lettre de gratitude",
    description:
      "Cette fiche PDF vous invite à écrire une lettre de gratitude pour exprimer votre reconnaissance envers quelqu'un ou quelque chose qui vous a fait du bien.",
    type: ["Observation", "Fichier", "Exercice"],
    themes: ["Bienveillance envers soi-même", "Reconnaître ses émotions", "Se relaxer", "Vie quotidienne"],
    audience: ["Pour tous"],
    url: "https://www.santementale-info-service.fr/en-prendre-soin/tous-les-exercices/lettre-de-gratitude",
    source: "Santé Mentale Info Service",
  },
  {
    id: "e5f6a7b8-c9d0-1234-9012-345678901234",
    title: "Activités pour prendre soin de sa santé mentale",
    description:
      "Cette fiche PDF vous invite à lister les activités que vous faites déjà pour prendre soin de votre bien-être mental, puis à réfléchir à des moyens de les pratiquer plus régulièrement.",
    type: ["Fichier", "Exercice"],
    themes: ["Vie quotidienne"],
    audience: ["Pour tous"],
    url: "https://www.santementale-info-service.fr/en-prendre-soin/tous-les-exercices/les-activites-pour-prendre-soin-de-ma-sante-mentale",
    source: "Santé Mentale Info Service",
  },
  {
    id: "f6a7b8c9-d0e1-2345-0123-456789012345",
    title: "Le questionnaire du sommeil",
    description:
      "Ce questionnaire en ligne, élaboré par des médecins et psychologues spécialistes, permet d'évaluer vos troubles du sommeil. Gratuit et anonyme, il génère un rapport et des conseils personnalisés.",
    type: ["Questionnaire"],
    themes: ["Améliorer son sommeil", "Diminuer le stress"],
    audience: ["Pour tous"],
    url: "https://questionnaire.reseau-morphee.fr/",
    source: "Reseau Morphée",
  },
  {
    id: "c9d0e1f2-a3b4-5678-4567-890123456789",
    title: "Décrocher des pensées négatives sur soi même",
    description:
      "Cet audio vous guide pour reconnaître vos pensées négatives sur vous-même et apprendre à leur répondre avec bienveillance. Grâce à des techniques simples, vous développez un regard plus doux sur vous-même.",
    type: ["Audio", "Exercice"],
    themes: ["Bienveillance envers soi-même", "Diminuer le stress", "Gérer les pensées difficiles", "Reconnaître ses émotions"],
    audience: ["Pour tous"],
    url: "https://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Unhooking_from_Unkind_Thoughts_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "d0e1f2a3-b4c5-6789-5678-901234567890",
    title: "Remarquer et nommer une pensée difficile",
    description:
      "Cet audio vous aide à identifier vos pensées envahissantes et à leur donner un nom. Grâce à plusieurs techniques simples, vous apprenez à prendre du recul, à réduire leur impact et à retrouver plus de clarté mentale au quotidien.",
    type: ["Audio", "Exercice"],
    themes: ["Diminuer le stress", "Gérer les pensées difficiles", "Reconnaître ses émotions", "Réguler ses émotions", "Se relaxer"],
    audience: ["Pour tous"],
    url: "https://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Notice_and_Name_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "e1f2a3b4-c5d6-7890-6789-012345678901",
    title: "Apprendre à faire le tri dans ses pensées",
    description:
      "Cet outil vous aide à reconnaître vos pensées anxieuses et à distinguer celles qui sont utiles de celles qui le sont moins. Il vous guide pour observer vos pensées sans vous laisser submerger, et adopter des réactions plus apaisées au quotidien.",
    type: ["Article"],
    themes: ["Diminuer le stress", "Gérer les pensées difficiles", "Reconnaître ses émotions", "Réguler ses émotions"],
    audience: ["Jeunes"],
    url: "https://fondationjeunesentete.org/ressource/anxiete-apprendre-a-faire-le-tri-dans-mes-pensees-pour-me-sentir-mieux/",
    source: "Fondation Jeunes en Tête",
  },
  {
    id: "f2a3b4c5-d6e7-8901-7890-123456789012",
    title: "S'ancrer dans le présent - 11 min",
    description:
      "Pendant onze minutes, cet exercice vous aide à vous ancrer dans le moment présent : observer vos pensées et émotions sans vous laisser emporter, et prêter attention à ce que vous êtes en train de faire.",
    type: ["Audio", "Exercice"],
    themes: ["Diminuer le stress", "Gérer les pensées difficiles", "Reconnaître ses émotions", "Réguler ses émotions", "Se relaxer"],
    audience: ["Pour tous"],
    url: "https://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Grounding_Exercise_3_10_minutes_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "a3b4c5d6-e7f8-9012-8901-234567890123",
    title: "S'ancrer dans le présent - 2 min",
    description:
      "Pendant deux minutes, cet exercice vous aide à vous ancrer dans le moment présent : observer vos pensées et émotions sans vous laisser emporter, et prêter attention à ce que vous êtes en train de faire.",
    type: ["Audio", "Exercice"],
    themes: ["Diminuer le stress", "Gérer les pensées difficiles", "Reconnaître ses émotions", "Réguler ses émotions", "Se relaxer"],
    audience: ["Pour tous"],
    url: "https://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Grounding_Exercise_2_2_minutes_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "d6e7f8a9-b0c1-2345-1234-567890123456",
    title: "Réguler ses émotions, mini jeu de l'action opposée",
    description:
      "Cet outil propose de répondre à vos émotions par des actions contraires à vos réactions habituelles. Par exemple, parler calmement quand vous êtes en colère ou regarder une comédie quand vous êtes triste, pour apaiser et transformer votre état émotionnel.",
    type: ["Jeu"],
    themes: ["Apprendre à se connaître", "Reconnaître ses émotions", "Réguler ses émotions"],
    audience: [["Jeunes"], ["Pour tous"]],
    url: "https://www.nightline.fr/kitdevie/fais-l-action-opposee/",
    source: "Nightline",
  },
  {
    id: "a9b0c1d2-e3f4-5678-4567-890123456789",
    title: "Exercice audio : faire de la place à ses émotions",
    description:
      "Cet audio vous guide pendant quelques minutes pour accueillir vos pensées, vos émotions et vos sensations difficiles. Plutôt que de lutter contre elles, vous apprenez à les observer avec curiosité, à les nommer et à leur offrir de l'espace.",
    type: ["Audio"],
    themes: ["Diminuer le stress", "Gérer les pensées difficiles", "Reconnaître ses émotions", "Réguler ses émotions", "Se relaxer"],
    audience: ["Pour tous"],
    url: "https://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Making_Room_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "e7f8a9b0-c1d2-3456-2345-678901234567",
    title: "Les stratégie parapluie en cas de crise",
    description:
      "En cas de crise, cette fiche vous propose des stratégies simples pour vous aider à vous calmer, faire une pause et reprendre vos esprits.",
    type: ["Fichier"],
    themes: ["Diminuer le stress", "Gérer les pensées difficiles", "Gérer une crise", "Réguler ses émotions", "Se relaxer"],
    audience: ["Jeunes", "Pour tous"],
    url: "https://cdn.fondationjeunesentete.org/wp-content/uploads/2020/11/09141604/FJET-FICHE-JEUNESSE_PARAPLUIE.pdf",
    source: "Fondation Jeunes en Tête",
  },
  {
    id: "f8a9b0c1-d2e3-4567-3456-789012345678",
    title: "Gérer ses émotions",
    description:
      "Cette vidéo présente les principales étapes pour apprendre à mieux gérer ses émotions : les comprendre, les identifier, les exprimer puis les réguler.",
    type: ["Vidéo", "Exercice"],
    themes: ["Diminuer le stress", "Gérer les pensées difficiles", "Reconnaître ses émotions", "Réguler ses émotions"],
    audience: ["Pour tous"],
    url: "https://www.youtube.com/watch?v=JqYJE6NEOms&list=PLUGg132D8DUzv2H04p0-AWB_L5aplMtbo&index=9",
    source: "Promotion Santé Normandie",
  },
  {
    id: "b0c1d2e3-f4a5-6789-5678-901234567890",
    title: "Prendre du recul sur ses émotions",
    description:
      "Cette page vous aide à prendre du recul sur vos émotions grâce à la pleine conscience et à la mentalisation. Elle vous aide à identifier ce que vous ressentez, à observer vos pensées, vos sensations corporelles, et à mieux comprendre vos relations avec les autres.",
    type: ["Article"],
    themes: ["Apprendre à se connaître", "Diminuer le stress", "Gérer les pensées difficiles", "Reconnaître ses émotions", "Se relaxer"],
    audience: ["Pour tous"],
    url: "https://fondationjeunesentete.org/ressource/mes-emotions/",
    source: "Fondation Jeunes en Tête",
  },
  {
    id: "c1d2e3f4-a5b6-7890-6789-012345678901",
    title: "Mini jeu : identifier ses émotions",
    description:
      "Ce jeu vous aide à identifier vos émotions - joie, colère, tristesse, peur, surprise ou dégoût - et à comprendre leur rôle. Il montre aussi comment elles se manifestent dans le corps, pour mieux les reconnaître et les apprivoiser.",
    type: ["Jeu"],
    themes: ["Apprendre à se connaître", "Reconnaître ses émotions", "Vie quotidienne"],
    audience: ["Jeunes", "Pour tous"],
    url: "https://www.nightline.fr/kitdevie/que-ressens-tu/",
    source: "Nightline",
  },
  {
    id: "d2e3f4a5-b6c7-8901-7890-123456789012",
    title: "Fiche mémo - Valeurs",
    description:
      "Cette fiche propose une liste de valeurs (authenticité, justice, liberté, générosité, courage, etc.) à cocher selon ce qui vous semble prioritaire. Elle vous aide à identifier ce qui compte vraiment pour vous et à orienter vos décisions de façon plus alignée.",
    type: ["Fichier"],
    themes: ["Apprendre à se connaître"],
    audience: ["Jeunes", "Pour tous"],
    url: "https://fondationjeunesentete.org/wp-content/uploads/2020/09/FJET-FICHE-JEUNESSE_MES-VALEURS.pdf",
    source: "Fondation Jeunes en Tête",
  },
  {
    id: "e3f4a5b6-c7d8-9012-8901-234567890123",
    title: "Vidéo d'animation - Les émotions",
    description:
      "Cette vidéo vous guide pour mieux cerner le fonctionnement de vos émotions : pourquoi elles apparaissent, comment elles évoluent et comment les exprimer de façon saine.",
    type: ["Vidéo"],
    themes: ["Apprendre à se connaître", "Gérer les pensées difficiles", "Reconnaître ses émotions", "Réguler ses émotions"],
    audience: ["Pour tous"],
    url: "http://youtube.com/watch?v=GzPuTLhQR2I&list=PLUGg132D8DUzv2H04p0-AWB_L5aplMtbo&index=4",
    source: "Promotion Santé Normandie",
  },
  {
    id: "f4a5b6c7-d8e9-0123-9012-345678901234",
    title: "l'application Wecare",
    description:
      "WeCare est une application pensée pour aider les jeunes adultes à prendre soin de leur santé mentale. À travers une aventure inspirée de la randonnée, elle propose des activités simples et guidées pour renforcer leurs ressources psychologiques, mieux comprendre leurs émotions et faire face aux défis du quotidien.",
    type: ["App"],
    themes: [
      "Apprendre à se connaître",
      "Diminuer le stress",
      "Gérer les pensées difficiles",
      "Reconnaître ses émotions",
      "Réguler ses émotions",
      "Se relaxer",
    ],
    audience: ["Jeunes"],
    url: "https://www.promotion-sante-bfc.org/projets/wecare",
    source: "Promotion Santé Bourgogne Franche-Comté",
  },
  {
    id: "a5b6c7d8-e9f0-1234-0123-456789012345",
    title: "Quizz du lutteur",
    description:
      "Quand on vit des émotions difficiles, on cherche parfois à les éviter ou à les faire disparaître rapidement. Mais cette lutte peut rendre les choses encore plus pénibles. Ce quizz vous aide à reconnaître vos réactions face à l'inconfort et à mieux comprendre ce réflexe de lutte.",
    type: ["Fichier", "Quizz"],
    themes: ["Apprendre à se connaître", "Gérer les pensées difficiles", "Reconnaître ses émotions"],
    audience: ["Jeunes"],
    url: "https://fondationjeunesentete.org/wp-content/uploads/2020/09/FJET-FICHE-JEUNESSE_QUIZ-DU-LUTTEUR.pdf",
    source: "Fondation Jeunes en Tête",
  },
  {
    id: "b6c7d8e9-f0a1-2345-1234-567890123456",
    title: `Vidéo d'animation "mieux se connaitre"`,
    description:
      "Cette vidéo vous invite à mieux vous connaître : comprendre vos émotions, vos valeurs et vos besoins profonds. Elle vous aide à clarifier ce qui compte pour vous, afin d'adopter une vie plus alignée et authentique.",
    type: ["Vidéo"],
    themes: ["Apprendre à se connaître", "Reconnaître ses besoins"],
    audience: ["Pour tous"],
    url: "https://www.youtube.com/watch?v=dB8w52M7H-c&list=PLUGg132D8DUzv2H04p0-AWB_L5aplMtbo&index=10",
    source: "Promotion Santé Normandie",
  },
  {
    id: "c7d8e9f0-a1b2-3456-2345-678901234567",
    title: "L'exercice audio de 8 mn pour être bienveillant envers vous-même",
    description:
      "Cet audio vous apprend à développer une attitude plus douce et compréhensive envers vous-même. En quelques minutes, vous explorez des techniques simples pour apaiser le stress, accueillir vos émotions et pratiquer l'auto-bienveillance au quotidien.",
    type: ["Audio"],
    themes: [
      "Bienveillance envers soi-même",
      "Diminuer le stress",
      "Gérer les pensées difficiles",
      "Reconnaître ses émotions",
      "Réguler ses émotions",
    ],
    audience: ["Pour tous"],
    url: "http://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Being_kind_to_yourself_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "d8e9f0a1-b2c3-4567-3456-789012345678",
    title: "L'auto-évaluation positive",
    description:
      "Cette vidéo vous aide à développer une attitude plus bienveillante envers vous-même. Elle vous invite à reconnaître vos qualités, vos compétences et vos forces, et à porter un regard plus positif sur qui vous êtes.",
    type: ["Vidéo"],
    themes: ["Apprendre à se connaître", "Bienveillance envers soi-même"],
    audience: ["Pour tous"],
    url: "https://www.youtube.com/watch?v=dc1Kh5cmL5M&list=PLUGg132D8DUzv2H04p0-AWB_L5aplMtbo&index=6",
    source: "Promotion Santé Normandie",
  },
];
