import { ToolItemType, ToolItemEntity, ToolItemTheme, ToolItemAudience } from "../../entities/ToolItem";

// Re-export types for backward compatibility
export type { ToolItemType, ToolItemEntity, ToolItemTheme, ToolItemAudience };

export const TOOL_BECK_ID = "b2d8c2f4-0f44-48c0-945a-6c6a0f3b9d3d";
export const GPS_IDS = ["e7163404-e1bd-4101-a8eb-616e58679460", "e7163404-e1bd-4101-a8eb-616e58679462", "e7163404-e1bd-4101-a8eb-616e58679464"];
export const TOOL_COHERENCE_CARDIAQUE_ID = "c079d02b-f744-4be4-8ede-386897ca3b89";

export const TOOLS_DATA: ToolItemEntity[] = [
  {
    id: "e7163404-e1bd-4101-a8eb-616e58679466",
    matomoId: 66,
    title: "Plan de crise par Hop ma liste",
    description: "Préparez un plan d’action personnel pour lutter contre les idées suicidaires, et enregistrez le dans Jardin Mental.",
    type: ["Questionnaire"],
    themes: ["Obtenir de l'aide", "Gérer une crise"],
    audience: ["child", "parent", "student"],
    source: "CHU Angers",
    innerPath: {
      text: "Créer mon plan de crise",
      path: "crisis-plan",
    },
  },
  {
    id: TOOL_BECK_ID,
    matomoId: 65,
    title: "Colonnes de Beck",
    description: `Beck est un exercice de thérapie cognitive consistant à analyser une situation en cinq colonnes (situation, émotions, pensées automatiques, biais cognitifs, réponse/pensée alternative) afin de restructurer ses pensées.
Cet exercice nécessite des explications afin de le réaliser. Nous vous recommandons d’en discuter préalablement avec un thérapeute.`,
    type: ["Exercice"],
    themes: ["Émotions & pensées"],
    audience: ["child", "parent", "student"],
    source: "Jardin Mental",
  },
  {
    id: "e7163404-e1bd-4101-a8eb-616e58679464",
    matomoId: 64,
    title: "Mon GPS Parents (version interactive)",
    themes: ["Gérer une crise", "Obtenir de l'aide"],
    audience: ["parent"],
    url: "https://www.psycom.org/wp-content/uploads/2023/11/PSYCOM_GPS_PARENTS_INTERACTIF.pdf",
    source: "Psycom",
    description:
      "Ce livret vise à faciliter l’expression et le respect des souhaits des parents en ce qui concerne leur parentalité et le soin apporté à leurs enfants, dans l’hypothèse où ils devraient être hospitalisés. Il permet d’anticiper l’organisation familiale, de préciser ce qui est important pour l’enfant et de coordonner l’accompagnement avec les proches et les professionnels.",
    type: ["Fichier"],
  },
  {
    id: "e7163404-e1bd-4101-a8eb-616e58679463",
    matomoId: 63,
    title: "Mon GPS Parents (version impression)",
    themes: ["Gérer une crise", "Obtenir de l'aide"],
    audience: ["parent"],
    url: "https://www.psycom.org/wp-content/uploads/2024/04/PSYCOM_GPS_PARENTS_IMPRESSION_DEF.pdf",
    source: "Psycom",
    description:
      "Ce livret vise à faciliter l’expression et le respect des souhaits des parents en ce qui concerne leur parentalité et le soin apporté à leurs enfants, dans l’hypothèse où ils devraient être hospitalisés. Il permet d’anticiper l’organisation familiale, de préciser ce qui est important pour l’enfant et de coordonner l’accompagnement avec les proches et les professionnels.",
    type: ["Fichier"],
  },
  {
    id: "e7163404-e1bd-4101-a8eb-616e58679462",
    matomoId: 62,
    title: "Mon GPS Ado/Jeune adulte (version interactive)",
    themes: ["Gérer une crise", "Obtenir de l'aide"],
    audience: ["child"],
    url: "https://www.psycom.org/wp-content/uploads/2023/11/PSYCOM_GPS_ADOS_INTERACTIF_2023.pdf",
    source: "Psycom",
    description:
      "Ce livret vise à faciliter l’expression et le respect des souhaits des adolescents et jeunes adultes concernant leurs soins, dans l’hypothèse où ils ne seraient plus en mesure de consentir. Il aide à anticiper les situations de crise, à repérer ce qui les soutient et à renforcer la communication avec les proches, l’école et les professionnels.",
    type: ["Fichier"],
  },
  {
    id: "e7163404-e1bd-4101-a8eb-616e58679461",
    matomoId: 61,
    title: "Mon GPS Ado/Jeune adulte (version impression)",
    themes: ["Gérer une crise", "Obtenir de l'aide"],
    audience: ["child"],
    url: "https://www.psycom.org/wp-content/uploads/2023/11/PSYCOM_GPS_ADOS_A-IMPRIMER_2023.pdf",
    source: "Psycom",
    description:
      "Ce livret vise à faciliter l’expression et le respect des souhaits des adolescents et jeunes adultes concernant leurs soins, dans l’hypothèse où ils ne seraient plus en mesure de consentir. Il aide à anticiper les situations de crise, à repérer ce qui les soutient et à renforcer la communication avec les proches, l’école et les professionnels.",
    type: ["Fichier"],
  },
  {
    id: "e7163404-e1bd-4101-a8eb-616e58679460",
    matomoId: 60,
    title: "Mon GPS (version interactive)",
    themes: ["Gérer une crise", "Obtenir de l'aide"],
    audience: ["child", "parent", "student"],
    url: "https://www.psycom.org/wp-content/uploads/2023/11/PSYCOM_GPS_VF_INTERACTIF_2023.pdf",
    source: "Psycom",
    description:
      "Ce livret vise à faciliter l’expression et le respect de vos souhaits concernant vos soins et votre accompagnement, dans l’hypothèse où vous ne seriez plus en mesure de consentir. Il permet d’anticiper une situation de crise, de clarifier ce qui est important pour vous et de soutenir le dialogue avec vos proches et les professionnels.",
    type: ["Fichier"],
  },
  {
    id: "e7163404-e1bd-4101-a8eb-616e58679459",
    matomoId: 59,
    title: "Mon GPS (version impression)",
    themes: ["Gérer une crise", "Obtenir de l'aide"],
    audience: ["child", "parent", "student"],
    url: "https://www.psycom.org/wp-content/uploads/2024/04/PSYCOM_GPS_VF_IMPRESSION_MAI2022.pdf",
    source: "Psycom",
    description:
      "Ce livret vise à faciliter l’expression et le respect de vos souhaits concernant vos soins et votre accompagnement, dans l’hypothèse où vous ne seriez plus en mesure de consentir. Il permet d’anticiper une situation de crise, de clarifier ce qui est important pour vous et de soutenir le dialogue avec vos proches et les professionnels.",
    type: ["Fichier"],
  },
  {
    id: "d6adb4d9-99ae-4a1d-8f1e-c0a7a044070a",
    matomoId: 58,
    title: "L'auto-évaluation positive",
    description:
      "Cette vidéo vous aide à développer une attitude plus bienveillante envers vous-même. Elle vous invite à reconnaître vos qualités, vos compétences et vos forces, et à porter un regard plus positif sur qui vous êtes. ",
    type: ["Vidéo"],
    themes: ["Bien-être & vie quotidienne"],
    audience: ["child", "parent", "student"],
    url: "https://www.youtube.com/watch?v=dc1Kh5cmL5M&list=PLUGg132D8DUzv2H04p0-AWB_L5aplMtbo&index=6",
    source: "Promotion Santé Normandie",
  },
  {
    id: "fe76c214-b72b-4901-8fbf-90eeafec645d",
    matomoId: 57,
    title: "L’exercice audio de 8 mn pour être bienveillant envers vous-même",
    description:
      "Cet audio vous apprend à développer une attitude plus douce et compréhensive envers vous-même. En quelques minutes, vous explorez des techniques simples pour apaiser le stress, accueillir vos émotions et pratiquer l’auto-bienveillance au quotidien.",
    type: ["Audio"],
    themes: ["Bien-être & vie quotidienne", "Émotions & pensées"],
    audience: ["child", "parent", "student"],
    url: "http://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Being_kind_to_yourself_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "6a2df7bf-7f87-467d-92be-0e773b8e237a",
    matomoId: 56,
    title: "Vidéo d’animation “mieux se connaitre”",
    description:
      "Cette vidéo vous invite à mieux vous connaître : comprendre vos émotions, vos valeurs et vos besoins profonds. Elle vous aide à clarifier ce qui compte pour vous, afin d’adopter une vie plus alignée et authentique.",
    type: ["Vidéo"],
    themes: ["Émotions & pensées"],
    audience: ["child", "parent", "student"],
    url: "https://www.youtube.com/watch?v=dB8w52M7H-c&list=PLUGg132D8DUzv2H04p0-AWB_L5aplMtbo&index=10",
    source: "Promotion Santé Normandie",
  },
  {
    id: "020bb041-0122-496c-9b10-a7e649408698",
    matomoId: 55,
    title: "Quizz du lutteur",
    description:
      "Quand on vit des émotions difficiles, on cherche parfois à les éviter ou à les faire disparaître rapidement. Mais cette lutte peut rendre les choses encore plus pénibles. Ce quizz vous aide à reconnaître vos réactions face à l’inconfort et à mieux comprendre ce réflexe de lutte.",
    type: ["Fichier", "Quizz"],
    themes: ["Émotions & pensées"],
    audience: ["child"],
    url: "https://fondationjeunesentete.org/wp-content/uploads/2020/09/FJET-FICHE-JEUNESSE_QUIZ-DU-LUTTEUR.pdf",
    source: "Fondation Jeunes en Tête",
  },
  {
    id: "b50dc509-1e7d-4b3e-8ff8-fb479df0c69d",
    matomoId: 54,
    title: "l’application Wecare",
    description:
      "WeCare est une application pensée pour aider les jeunes adultes à prendre soin de leur santé mentale. À travers une aventure inspirée de la randonnée, elle propose des activités simples et guidées pour renforcer leurs ressources psychologiques, mieux comprendre leurs émotions et faire face aux défis du quotidien.",
    type: ["App"],
    themes: ["Émotions & pensées", "Bien-être & vie quotidienne"],
    audience: ["child"],
    url: "https://www.promotion-sante-bfc.org/projets/wecare",
    source: "Promotion Santé Bourgogne Franche-Comté",
  },
  {
    id: "2c62b27b-961a-4ea2-98e4-69d87ae7f1ca",
    matomoId: 53,
    title: "Vidéo d’animation - Les émotions",
    description:
      "Cette vidéo vous guide pour mieux cerner le fonctionnement de vos émotions : pourquoi elles apparaissent, comment elles évoluent et comment les exprimer de façon saine. ",
    type: ["Vidéo"],
    themes: ["Émotions & pensées"],
    audience: ["child", "parent", "student"],
    url: "https://youtube.com/watch?v=GzPuTLhQR2I&list=PLUGg132D8DUzv2H04p0-AWB_L5aplMtbo&index=4",
    source: "Promotion Santé Normandie",
  },
  {
    id: "a8f8e15d-2766-4f46-9f55-7fb823afb3c6",
    matomoId: 52,
    title: "Fiche mémo - Valeurs",
    description:
      "Cette fiche propose une liste de valeurs (authenticité, justice, liberté, générosité, courage, etc.) à cocher selon ce qui vous semble prioritaire. Elle vous aide à identifier ce qui compte vraiment pour vous et à orienter vos décisions de façon plus alignée.",
    type: ["Fichier"],
    themes: ["Émotions & pensées"],
    audience: ["child", "parent", "student"],
    url: "https://fondationjeunesentete.org/wp-content/uploads/2020/09/FJET-FICHE-JEUNESSE_MES-VALEURS.pdf",
    source: "Fondation Jeunes en Tête",
  },
  {
    id: "b0daf11b-65c7-4059-a598-790424cb2bdd",
    matomoId: 51,
    title: "Mini jeu : identifier ses émotions",
    description:
      "Ce jeu vous aide à identifier vos émotions - joie, colère, tristesse, peur, surprise ou dégoût - et à comprendre leur rôle. Il montre aussi comment elles se manifestent dans le corps, pour mieux les reconnaître et les apprivoiser.",
    type: ["Jeu"],
    themes: ["Émotions & pensées"],
    audience: ["child", "parent", "student"],
    url: "https://www.nightline.fr/kitdevie/que-ressens-tu/",
    source: "Nightline",
  },
  {
    id: "119fe26f-b62c-48b2-bdb2-6df24693b912",
    matomoId: 50,
    title: "Prendre du recul sur ses émotions",
    description:
      "Cette page vous aide à prendre du recul sur vos émotions grâce à la pleine conscience et à la mentalisation. Elle vous aide à identifier ce que vous ressentez, à observer vos pensées, vos sensations corporelles, et à mieux comprendre vos relations avec les autres.",
    type: ["Article"],
    themes: ["Émotions & pensées"],
    audience: ["child", "parent", "student"],
    url: "https://fondationjeunesentete.org/ressource/mes-emotions/",
    source: "Fondation Jeunes en Tête",
  },
  {
    id: "61805a1e-6a41-4e3e-9a3c-098bbb06bb5e",
    matomoId: 49,
    title: "Exercice audio : faire de la place à ses émotions",
    description:
      "Cet audio vous guide pendant quelques minutes pour accueillir vos pensées, vos émotions et vos sensations difficiles. Plutôt que de lutter contre elles, vous apprenez à les observer avec curiosité, à les nommer et à leur offrir de l’espace.",
    type: ["Audio"],
    themes: ["Émotions & pensées"],
    audience: ["child", "parent", "student"],
    url: "https://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Making_Room_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "aaf3e6c2-8c9a-4fdc-a926-0dfd0bf99da0",
    matomoId: 48,
    title: "Gérer ses émotions",
    description:
      "Cette vidéo présente les principales étapes pour apprendre à mieux gérer ses émotions : les comprendre, les identifier, les exprimer puis les réguler.",
    type: ["Vidéo", "Exercice"],
    themes: ["Émotions & pensées"],
    audience: ["child", "parent", "student"],
    url: "https://www.youtube.com/watch?v=JqYJE6NEOms&list=PLUGg132D8DUzv2H04p0-AWB_L5aplMtbo&index=9",
    source: "Promotion Santé Normandie",
  },
  {
    id: "99d8f878-7000-4a87-808d-8d74fa4ce1f3",
    matomoId: 47,
    title: "La stratégie parapluie en cas de crise",
    description:
      "En cas de crise, cette fiche vous propose des stratégies simples pour vous aider à vous calmer, faire une pause et reprendre vos esprits.",
    type: ["Fichier"],
    themes: ["Gérer une crise"],
    audience: ["child", "parent", "student"],
    url: "https://cdn.fondationjeunesentete.org/wp-content/uploads/2020/11/09141604/FJET-FICHE-JEUNESSE_PARAPLUIE.pdf",
    source: "Fondation Jeunes en Tête",
  },
  {
    id: "0c2a10ef-1730-4d08-9718-3fc96ebfc9a4",
    matomoId: 46,
    title: "Réguler ses émotions, mini jeu de l’action opposée",
    description:
      "Cet outil propose de répondre à vos émotions par des actions contraires à vos réactions habituelles. Par exemple, parler calmement quand vous êtes en colère ou regarder une comédie quand vous êtes triste, pour apaiser et transformer votre état émotionnel.",
    type: ["Jeu"],
    themes: ["Émotions & pensées"],
    audience: ["child", "parent", "student"],
    url: "https://www.nightline.fr/kitdevie/fais-l-action-opposee/",
    source: "Nightline",
  },
  {
    id: "a085c3cf-1bb6-47ee-8d0f-dc82d590bf08",
    matomoId: 45,
    title: "Maintenir son attention sur le présent : Exercice “Conscience de boire”",
    description:
      "Pendant huit minutes, cet exercice vous aide à vous ancrer dans le moment présent : observer vos pensées et émotions sans vous laisser emporter, et prêter attention à ce que vous êtes en train de faire.",
    type: ["Audio", "Exercice"],
    themes: ["Émotions & pensées", "Gérer le stress"],
    audience: ["child", "parent", "student"],
    url: "https://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Awareness_of_Drinking_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "909a6674-4826-45b4-bf58-f7869a258efc",
    matomoId: 43,
    title: "S’ancrer dans le présent -  6 min",
    description:
      "Pendant deux minutes, cet exercice vous aide à vous ancrer dans le moment présent : observer vos pensées et émotions sans vous laisser emporter, et prêter attention à ce que vous êtes en train de faire.",
    type: ["Audio", "Exercice"],
    themes: ["Émotions & pensées", "Gérer le stress"],
    audience: ["child", "parent", "student"],
    url: "https://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Grounding_Exercise_2_2_minutes_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "226e7573-a86d-4dfe-8deb-63ae05d37b97",
    matomoId: 44,
    title: "S’ancrer dans le présent - 2 min",
    description:
      "Pendant six minutes, cet exercice vous aide à vous ancrer dans le moment présent : observer vos pensées et émotions sans vous laisser emporter, et prêter attention à ce que vous êtes en train de faire.",
    type: ["Audio", "Exercice"],
    themes: ["Émotions & pensées", "Gérer le stress"],
    audience: ["child", "parent", "student"],
    url: "https://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Grounding_Exercise_1__5_minutes_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "1538284a-2857-494e-aaf1-6d6057130925",
    matomoId: 42,
    title: "S’ancrer dans le présent - 11 min",
    description:
      "Pendant onze minutes, cet exercice vous aide à vous ancrer dans le moment présent : observer vos pensées et émotions sans vous laisser emporter, et prêter attention à ce que vous êtes en train de faire.",
    type: ["Audio", "Exercice"],
    themes: ["Émotions & pensées", "Gérer le stress"],
    audience: ["child", "parent", "student"],
    url: "https://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Grounding_Exercise_3_10_minutes_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "6a875d39-af21-46ad-8426-4e6094e57562",
    matomoId: 41,
    title: "Apprendre à faire le tri dans ses pensées",
    description:
      "Cet outil vous aide à reconnaître vos pensées anxieuses et à distinguer celles qui sont utiles de celles qui le sont moins. Il vous guide pour observer vos pensées sans vous laisser submerger, et adopter des réactions plus apaisées au quotidien.",
    type: ["Article"],
    themes: ["Émotions & pensées"],
    audience: ["child"],
    url: "https://fondationjeunesentete.org/ressource/anxiete-apprendre-a-faire-le-tri-dans-mes-pensees-pour-me-sentir-mieux/",
    source: "Fondation Jeunes en Tête",
  },
  {
    id: "b2b57433-66e5-4e9b-9fd3-efe7daaee834",
    matomoId: 40,
    title: "Remarquer et nommer une pensée difficile",
    description:
      "Cet audio vous aide à identifier vos pensées envahissantes et à leur donner un nom. Grâce à plusieurs techniques simples, vous apprenez à prendre du recul, à réduire leur impact et à retrouver plus de clarté mentale au quotidien.",
    type: ["Audio", "Exercice"],
    themes: ["Émotions & pensées"],
    audience: ["child", "parent", "student"],
    url: "https://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Notice_and_Name_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "0189eb22-b0e4-4b46-a684-d3723ed57a83",
    matomoId: 39,
    title: "Décrocher des pensées négatives sur soi même",
    description:
      "Cet audio vous guide pour reconnaître vos pensées négatives sur vous-même et apprendre à leur répondre avec bienveillance. Grâce à des techniques simples, vous développez un regard plus doux sur vous-même. ",
    type: ["Audio", "Exercice"],
    themes: ["Émotions & pensées"],
    audience: ["child", "parent", "student"],
    url: "https://terrance.who.int/mediacentre/audio/MSD/Doing_What_Matters_French/WHO-AUDIO_Stress_Management_Unhooking_from_Unkind_Thoughts_FRENCH_22OCT2020.mp3",
    source: "Organisation Mondiale de la Santé (OMS)",
  },
  {
    id: "fe23469f-0601-4cf0-8dca-9bde16412c68",
    matomoId: 38,
    title: "Comprendre mes biais de pensée : prendre de la distance",
    description:
      "Cet outil vous aide à repérer les biais de pensée - ces façons de penser qui peuvent déformer la réalité et alimenter des émotions négatives. Après la présentation du concept, un exercice pratique se trouve tout à la fin de la page pour vous entraîner à les identifier et prendre du recul.",
    type: ["Article", "Jeu", "Quizz"],
    themes: ["Émotions & pensées"],
    audience: ["child", "parent", "student"],
    url: "https://www.nightline.fr/kit-de-vie/comprendre-mes-biais-de-pensee",
    source: "Nightline",
  },
  {
    id: "5a20bba1-068f-457f-92ce-9d7bff4c3879",
    matomoId: 37,
    title: "Résoudre ses problèmes avec la méthode PROPS",
    description:
      "Cette vidéo présente la méthode PROPS (Pause, Réflexion, Options, Priorité, Stratégie) - un guide pas à pas pour apprendre à gérer une situation. Elle vous montre comment prendre du recul, explorer différentes options et choisir une stratégie efficace pour agir avec clarté et confiance.",
    type: ["Vidéo"],
    themes: ["Bien-être & vie quotidienne"],
    audience: ["child", "parent", "student"],
    url: "https://www.youtube.com/watch?v=z5QsLht3MIY&list=PLUGg132D8DUzv2H04p0-AWB_L5aplMtbo&index=12",
    source: "Promotion Santé Normandie",
  },
  {
    id: "094e210e-c4fd-423c-8cb3-4bd0d9d62266",
    matomoId: 36,
    title: "Le questionnaire du sommeil",
    description:
      "Ce questionnaire en ligne, élaboré par des médecins et psychologues spécialistes, permet d’évaluer vos troubles du sommeil. Gratuit et anonyme, il génère un rapport et des conseils personnalisés. ",
    type: ["Questionnaire"],
    themes: ["Sommeil"],
    audience: ["child", "parent", "student"],
    url: "https://questionnaire.reseau-morphee.fr/",
    source: "Reseau Morphée",
  },
  {
    id: "704a211f-e794-4496-af1f-8b494dfe184b",
    matomoId: 35,
    title: "Activités pour prendre soin de sa santé mentale",
    description:
      "Cette fiche PDF vous invite à lister les activités que vous faites déjà pour prendre soin de votre bien‑être mental, puis à réfléchir à des moyens de les pratiquer plus régulièrement.",
    type: ["Fichier", "Exercice"],
    themes: ["Bien-être & vie quotidienne"],
    audience: ["child", "parent", "student"],
    url: "https://www.santementale-info-service.fr/sites/default/files/2025-05/Santementale_Activite%CC%81-qui-me-font-du-bien_0.pdf",
    source: "Santé Mentale Info Service",
  },
  {
    id: "7525f496-a44d-47c5-96a0-54fd64246795",
    matomoId: 34,
    title: "Lettre de gratitude",
    description:
      "Cette fiche PDF vous invite à écrire une lettre de gratitude pour exprimer votre reconnaissance envers quelqu’un ou quelque chose qui vous a fait du bien. ",
    type: ["Fichier", "Exercice", "Observation"],
    themes: ["Bien-être & vie quotidienne"],
    audience: ["child", "parent", "student"],
    url: "https://www.santementale-info-service.fr/sites/default/files/2025-05/Santementale_Lettre-de-gratitude_0.pdf",
    source: "Santé Mentale Info Service",
  },
  {
    id: "6590e1f3-2acb-40ce-80ee-c5e084f85aa0",
    matomoId: 33,
    title: "Journal de gratitude",
    description:
      "Cette fiche PDF consiste à tenir un journal de gratitude, en notant régulièrement les moments positifs, les personnes ou les événements pour lesquels vous vous sentez reconnaissant.",
    type: ["Fichier", "Exercice", "Observation"],
    themes: ["Bien-être & vie quotidienne"],
    audience: ["child", "parent", "student"],
    url: "https://www.santementale-info-service.fr/sites/default/files/2025-05/Santementale_Journal-de-gratitude_0.pdf",
    source: "Santé Mentale Info Service",
  },
  {
    id: "6aff57dc-bf65-4bba-9a36-d4af8182c88c",
    matomoId: 32,
    title: "Journal du sommeil",
    description:
      "Cette fiche PDF vous invite à suivre votre sommeil jour après jour. Elle permet d’identifier vos habitudes, de repérer les facteurs qui perturbent votre sommeil, et de mieux comprendre comment améliorer vos nuits.",
    type: ["Fichier", "Exercice", "Observation"],
    themes: ["Sommeil"],
    audience: ["child", "parent", "student"],
    url: "https://www.santementale-info-service.fr/sites/default/files/2025-05/Santementale_Journal-du-sommeil_0.pdf",
    source: "Santé Mentale Info Service",
  },
  {
    id: TOOL_COHERENCE_CARDIAQUE_ID,
    matomoId: 31,
    title: "Cohérence cardiaque",
    description:
      "Cet exercice vidéo vous guide dans une respiration rythmée : inspirez lorsque la bulle monte, expirez lorsqu’elle descend. Pratiqué assis et détendu, il permet de calmer le corps et l’esprit, de réduire le stress et de retrouver rapidement une sensation d’apaisement.",
    type: ["Vidéo", "Exercice"],
    themes: ["Gérer le stress", "Gérer une crise"],
    audience: ["child", "parent", "student"],
    url: "https://www.santementale-info-service.fr/en-prendre-soin/tous-les-exercices/coherence-cardiaque",
    source: "Santé Mentale Info Service",
    embed: "breath-exercice",
    video: "coherence-cardiaque-video",
  },
  {
    id: "ef432c51-14af-4d91-af85-7a7dc751dceb",
    matomoId: 30,
    title: "Relaxation musculaire",
    description:
      "Cet exercice audio vous guide pour détendre vos muscles en les contractant puis en les relâchant progressivement. Il permet de relâcher les tensions et de favoriser un état de calme et de détente.",
    type: ["Audio", "Exercice"],
    themes: ["Gérer le stress"],
    audience: ["child", "parent", "student"],
    url: "https://www.santementale-info-service.fr/en-prendre-soin/tous-les-exercices/relaxation-musculaire",
    source: "Santé Mentale Info Service",
  },
  {
    id: "a3029ba7-f934-44cd-ac09-9b323e41b1ff",
    matomoId: 29,
    title: "Consommation d’alcool : Questionnaire FACE",
    description:
      "Le questionnaire FACE (fast alcohol consumption evaluation) vous permet d’autoévaluer vos habitudes de consommation d’alcool de façon anonyme et guidée. ",
    type: ["Questionnaire"],
    themes: ["Addictions"],
    audience: ["child", "parent", "student"],
    url: "https://www.addictaide.fr/parcours/face/?quest=true#/face",
    source: "Addict'AIDE",
  },
  {
    id: "f6b57368-1a10-4b7e-9211-3d3606f120cd",
    matomoId: 28,
    title: "Se former au secourisme en santé mentale",
    description:
      "PSSM Formation propose des formations aux « Premiers Secours en Santé Mentale » pour :  apprendre à reconnaître les signes de détresse psychique, écouter sans jugement, soutenir une personne en crise et l’orienter vers de l’aide.",
    type: ["Formation"],
    themes: ["Obtenir de l'aide"],
    audience: ["child", "parent", "student"],
    url: "https://www.pssmformation.fr/",
    source: "PSSM",
  },
  {
    id: "0333ed1f-bc5a-4d3f-b487-49bae661e669",
    matomoId: 27,
    title: "Carte des lieux pour trouver de l’aide ",
    description:
      "Ce site répertorie des ressources fiables pour trouver de l’aide en santé mentale : professionnels (psychiatres, psychologues), associations, numéros d’écoute et dispositifs publics. Il vous guide vers des solutions adaptées selon votre situation.",
    type: ["Carte"],
    themes: ["Obtenir de l'aide"],
    audience: ["child", "parent", "student"],
    url: "https://www.sante.fr/sante-mentale-2/ou-trouver-de-laide",
    source: "Santé.fr",
  },
  {
    id: "87c88513-9fc2-476d-94e4-957f7925825e",
    matomoId: 26,
    title: "Respirelax ",
    description:
      "Cette application propose des exercices guidés de cohérence cardiaque pour calmer le corps et l’esprit. Elle aide à réduire le stress, favoriser la détente et propose des séances adaptables à votre niveau, disponibles hors-ligne.",
    type: ["App"],
    themes: ["Gérer le stress"],
    audience: ["child", "parent", "student"],
    url: "https://www.thermes-allevard.com/content/respirelax-0",
    source: "Thermes Allevard",
  },
  {
    id: "d4bcc28f-a17a-4ce4-bdaf-e6901cc217c9",
    matomoId: 25,
    title: "Hop Ma Liste ",
    description:
      "Cette application vous aide à traverser les moments de crise : identifier vos signes d’alerte, activer vos stratégies de soutien, et accéder à des ressources et messages positifs pour vous calmer et vous protéger.",
    type: ["App"],
    themes: ["Obtenir de l'aide", "Gérer une crise"],
    audience: ["child", "parent", "student"],
    url: "https://www.chu-angers.fr/offre-de-soins/acteur-de-sante-publique/hop-ma-liste-134448.kjsp?",
    source: "CHU Angers",
  },
  {
    id: "7d6fcd2a-e330-4113-8b40-0d106603a55e",
    matomoId: 24,
    title: "Les activités individuelles créatives de l’Etonnant Periple",
    description:
      "Ce cahier propose des activités positives co‑construits avec des personnes concernées par des troubles psychiques. Il est conçu pour favoriser l’affirmation de soi, la connaissance de soi et le bien‑être.",
    type: ["Article"],
    themes: ["Bien-être & vie quotidienne"],
    audience: ["child", "parent", "student"],
    url: "https://etonnant-periple.fr/activites-individuelles/",
    source: "Etonnant Périple",
  },
  {
    id: "9bf3a26f-5085-47d7-ac8b-b765bddb597b",
    matomoId: 23,
    title: "Les livrets d’auto-soin du CCR",
    description:
      "Ces livrets d’auto‑soin proposent des exercices pratiques pour mieux gérer vos émotions, vos pensées, votre sommeil et vos activités quotidiennes. Ils aident aussi à réfléchir sur soi et à renforcer votre bien‑être, à votre rythme, que vous viviez ou non un trouble psychique.",
    type: ["Article"],
    themes: ["Émotions & pensées", "Bien-être & vie quotidienne", "Gérer une crise", "Sommeil", "Obtenir de l'aide"],
    audience: ["child", "parent", "student"],
    url: "https://centre-ressource-rehabilitation.org/outil-livrets-d-auto-soin",
    source: "Centre Ressources de Réhabilitation Psychosociale",
  },
  {
    id: "e7163404-e1bd-4101-a8eb-616e586794e5",
    matomoId: 22,
    title: "Plan personnel de gestion de crise",
    description:
      "Ce livret vous aide à préparer un plan de gestion de crise : repérer vos signes d’alerte, identifier ce qui peut vous apaiser, et noter les personnes ou services à contacter si vous traversez une situation très difficile.",
    type: ["Fichier"],
    themes: ["Obtenir de l'aide", "Gérer une crise"],
    audience: ["child", "parent", "student"],
    url: "https://ateliers-rehab.ch/docs/revim/REVIM_Mon-plan-de-gestion-de-crise-2025.pdf",
    source: "Centre Ressources de Réhabilitation Psychosociale",
  },
  {
    id: "13547522-e7d8-477e-be64-4161f1cf5f7b",
    matomoId: 21,
    title: "MyClepsy",
    description:
      "CléPsy est un site conçu pour accompagner les parents au quotidien dans leur parentalité et la santé mentale de leurs enfants. Il propose aussi un assistant virtuel de guidance parentale accessible via Whatsapp.",
    type: ["Chatbot"],
    themes: ["Obtenir de l'aide"],
    audience: ["parent"],
    url: "https://www.clepsy.fr/",
    source: "CléPsy",
  },
  {
    id: "504549ce-59af-49ab-a8e1-bff21bb6685d",
    matomoId: 20,
    title: "Agir sur mes comportements",
    description:
      "Cet outil vous aide à identifier des activités positives et à les intégrer dans votre quotidien. Il propose des stratégies simples pour agir sur vos comportements, rester motivé et renforcer votre bien-être, même dans les moments difficiles.",
    type: ["Article", "Jeu"],
    themes: ["Bien-être & vie quotidienne"],
    audience: ["child", "parent", "student"],
    url: "https://www.nightline.fr/kit-de-vie/agir-sur-mes-comportements",
    source: "Nightline",
  },
  {
    id: "c8e917ae-dc2d-43d3-8b20-64aa0d1e4673",
    matomoId: 19,
    title: "Découvrir la méditation",
    description: "Cette méditation courte vous aide à vous poser, prendre quelques instants pour respirer et revenir au moment présent.",
    type: ["Vidéo"],
    themes: ["Gérer le stress"],
    audience: ["child", "parent", "student"],
    url: "https://www.youtube.com/watch?v=rlKe8dGsEko&embeds_referring_euri=https%3A%2F%2Fwww.nightline.fr%2F&source_ve_path=MjM4NTE",
    source: "Nightline",
  },
  {
    id: "0bcf2910-d23d-4efa-8d1d-a6b637d87e1e",
    matomoId: 18,
    title: "Crise de calme",
    description:
      "Si vous trouvez la méditation difficile, vous pouvez essayer la crise de calme : une vidéo courte de 3 minutes qui vous aide à retrouver rapidement calme et apaisement.",
    type: ["Vidéo"],
    themes: ["Gérer le stress", "Gérer une crise"],
    audience: ["child", "parent", "student"],
    url: "https://www.youtube.com/watch?v=9VUp582KRH8",
    source: "Nightline",
  },
  {
    id: "03d2065a-aaa2-40ef-acc9-1955f98d2d3e",
    matomoId: 17,
    title: "Body Scan",
    description:
      "Cette vidéo propose un body scan, un exercice de pleine conscience consistant à porter votre attention sur différentes parties de votre corps, de la tête aux pieds. Il permet de relâcher les tensions, d’améliorer la conscience corporelle et de favoriser un état de calme et de détente.",
    type: ["Vidéo"],
    themes: ["Gérer le stress"],
    audience: ["child", "parent", "student"],
    url: "https://www.youtube.com/watch?v=D89hIkSRvnY",
    source: "Nightline",
  },
  {
    id: "e423bb51-e977-4b51-a12c-aa8a3d3ea9bb",
    matomoId: 16,
    title: "Poser ses maux",
    description:
      "Cet outil vous permet d’écrire ce que vous ressentez quand le mal-être est flou : un mini‑jeu vous aide à choisir des mots qui correspondent à votre ressenti, puis à les transformer en un message. Vous pouvez conserver ce texte ou l’envoyer à une personne de confiance.",
    type: ["Jeu"],
    themes: ["Émotions & pensées"],
    audience: ["child", "parent", "student"],
    url: "https://www.nightline.fr/kit-de-vie/poser-ses-maux",
    source: "Nightline",
  },
  {
    id: "856a57d6-44f5-4d19-b2ad-4dedf159ba1c",
    matomoId: 15,
    title: "Réseau des centres du sommeil",
    description:
      "Cette page liste les centres du sommeil agréés en France pour diagnostiquer et traiter les troubles du sommeil.  Elle propose une cartographie des structures, ainsi que les coordonnées des centres spécialisés dans chaque région.",
    type: ["Carte"],
    themes: ["Sommeil", "Obtenir de l'aide"],
    audience: ["child", "parent", "student"],
    url: "https://institut-sommeil-vigilance.org/ou-consulter-reseau-sommeil-france/",
    source: "INSV",
  },
  {
    id: "074fbb36-f99c-4569-bc21-8607a0e49772",
    matomoId: 14,
    title: "Workaholisme (dépendance au travail) - Test WART",
    description:
      "Ce questionnaire WART (Work Addiction Risk Test) vous permet d’évaluer votre rapport au travail : il aide à caractériser un engagement excessif ou un “workaholisme” grâce à 25 questions.",
    type: ["Questionnaire"],
    themes: ["Addictions"],
    audience: ["child", "parent", "student"],
    url: "https://www.addictaide.fr/parcours/wart/",
    source: "Addict'AIDE",
  },
  {
    id: "dbdb8570-4c35-4fcb-8825-241913e4b2b8",
    matomoId: 13,
    title: "Évaluez votre risque d’addiction à l’alcool (Questionnaire AUDIT)",
    description:
      "Ce questionnaire AUDIT vous permet d’évaluer votre consommation d’alcool et les risques associés. Il est basé sur 10 questions validées par l’OMS et aide à mieux comprendre votre relation avec l’alcool.",
    type: ["Questionnaire"],
    themes: ["Addictions"],
    audience: ["child", "parent", "student"],
    url: "https://www.addictaide.fr/parcours/audit/",
    source: "Addict'AIDE",
  },
  {
    id: "35c2ffd4-9217-48b2-9ed4-9bbeb5f2b3b2",
    matomoId: 12,
    title: "Quantifiez votre niveau de dépendance au tabac (Test de Fagerström)",
    description:
      "Ce questionnaire mesure votre niveau de dépendance au tabac. Basé sur le test de Fagerström, il calcule un score (de 0 à 10) qui indique si votre dépendance est faible, moyenne ou forte.",
    type: ["Questionnaire"],
    themes: ["Addictions"],
    audience: ["child", "parent", "student"],
    url: "https://www.addictaide.fr/parcours/fagerstrom/",
    source: "Addict'AIDE",
  },
  {
    id: "f600f311-b1d7-4470-a723-96de822db6df",
    matomoId: 11,
    title: "Évaluez votre motivation à arrêter de fumer (Test de Lagrue et Légeron)",
    description:
      "Ce test calcule votre niveau de motivation à arrêter de fumer. Il se base sur 4 questions développées par Lagrue et Légeron : un score élevé signifie une motivation forte, un score faible indique que vous êtes moins prêt à quitter le tabac.",
    type: ["Questionnaire"],
    themes: ["Addictions"],
    audience: ["child", "parent", "student"],
    url: "https://www.addictaide.fr/parcours/lagrue/",
    source: "Addict'AIDE",
  },
  {
    id: "568b135e-2ae9-476b-8505-1b6b48ec8150",
    matomoId: 10,
    title: "Mesurez vos chances de réussite du sevrage tabagique (Test Demaria-Grimaldi-Lagrue)",
    description:
      "Ce questionnaire (Test de Demaria‑Grimaldi‑Lagrue) mesure vos chances de réussite à arrêter de fumer. Il se compose de 17 questions (oui/non) et vous aide à évaluer votre motivation et le bon moment pour entreprendre un sevrage tabagique.",
    type: ["Questionnaire"],
    themes: ["Addictions"],
    audience: ["child", "parent", "student"],
    url: "https://www.addictaide.fr/parcours/demaria/",
    source: "Addict'AIDE",
  },
  {
    id: "32c1900a-1759-40af-9905-500600706445",
    matomoId: 9,
    title: "Évaluez un usage nocif de cannabis (Test ALAC)",
    description:
      "Ce questionnaire ALAC vous permet d’évaluer votre consommation de cannabis et d’identifier un usage potentiellement nocif. Il s’agit d’un auto‑test simple et rapide pour prendre conscience de votre rapport à cette substance.",
    type: ["Questionnaire"],
    themes: ["Addictions"],
    audience: ["child", "parent", "student"],
    url: "https://www.addictaide.fr/parcours/alac/",
    source: "Addict'AIDE",
  },
  {
    id: "a99a612e-f8a7-41a7-be0d-9e371bccae2f",
    matomoId: 8,
    title: "Mesurez votre consommation de cannabis (Questionnaire CAST)",
    description:
      "Ce questionnaire mesure votre consommation de cannabis avec le test CAST (Cannabis Abuse Screening Test) : 6 questions pour identifier un usage potentiellement problématique.",
    type: ["Questionnaire"],
    themes: ["Addictions"],
    audience: ["child", "parent", "student"],
    url: "https://www.addictaide.fr/parcours/cast/",
    source: "Addict'AIDE",
  },
  {
    id: "8b86db97-c00c-40b0-ae72-896cd436a733",
    matomoId: 7,
    title: "Mesurez votre dépendance aux jeux vidéo (Game Addiction Scale)",
    description:
      "Ce questionnaire GAS (Game Addiction Scale) vous permet d’évaluer votre dépendance aux jeux vidéo à travers 7 questions sur vos habitudes de jeu au cours des 6 derniers mois. ",
    type: ["Questionnaire"],
    themes: ["Addictions"],
    audience: ["child", "parent", "student"],
    url: "https://www.addictaide.fr/parcours/gas/",
    source: "Addict'AIDE",
  },
  {
    id: "57f87c65-9e22-41ac-b7bf-1c3d3361fcae",
    matomoId: 6,
    title: "Évaluez votre usage d’internet (Internet - Test IAT)",
    description:
      "Ce test (Internet Addiction Test – IAT) vous permet d’évaluer si votre usage d’internet est excessif : 20 questions pour mesurer la dépendance et ses impacts sur votre vie quotidienne.",
    type: ["Questionnaire"],
    themes: ["Addictions"],
    audience: ["child", "parent", "student"],
    url: "https://www.addictaide.fr/parcours/internet/",
    source: "Addict'AIDE",
  },
  {
    id: "4f0c5c60-7e92-497d-b072-43e6a6586ec2",
    matomoId: 5,
    title: "Évaluez votre niveau de dépendance aux jeux d’argent et de hasard (Test ICJE)",
    description:
      "Ce questionnaire évalue votre dépendance aux jeux d’argent et de hasard via 9 questions. Il permet de mesurer le risque et d’identifier un usage problématique.",
    type: ["Questionnaire"],
    themes: ["Addictions"],
    audience: ["child", "parent", "student"],
    url: "https://www.addictaide.fr/parcours/icje/",
    source: "Addict'AIDE",
  },
  {
    id: "93c3ac2c-6aa9-48f5-b99a-af9fd715af63",
    matomoId: 4,
    title: "Repérez les usages nocifs de substances psychoactives chez les adolescents et jeunes adultes (Test ADOSPA)",
    description:
      "Le test ADOSPA est un questionnaire pour dépister précocement les usages à risque ou nocifs d’alcool et de drogues chez les jeunes. Il comporte 6 questions, et un score supérieur à 3 indique un risque élevé.",
    type: ["Questionnaire"],
    themes: ["Addictions"],
    audience: ["child", "parent"],
    url: "https://www.addictaide.fr/parcours/craft/",
    source: "Addict'AIDE",
  },
  {
    id: "cba4f7cf-35c8-4a76-8bc0-f63471448f13",
    matomoId: 3,
    title: "Évaluez la gravité d'une addiction",
    description:
      "Ce test permet d’évaluer la gravité d’une addiction - qu’elle soit liée à une substance ou à un comportement - selon quatre niveaux : absente, légère, modérée ou sévère. ",
    type: ["Questionnaire"],
    themes: ["Addictions"],
    audience: ["child", "parent", "student"],
    url: "https://www.addictaide.fr/parcours/gravite/",
    source: "Addict'AIDE",
  },
  {
    id: "e103393c-da01-4d71-980e-59a1b002871d",
    matomoId: 2,
    title: "Identifier le professionnel de santé adapté",
    description:
      "PRIMO est un questionnaire d’auto‑évaluation pour les jeunes. Il aide à identifier des signes de souffrance psychique, à mieux comprendre vos émotions et à être orienté vers des ressources ou professionnels adaptés.",
    type: ["Questionnaire"],
    themes: ["Obtenir de l'aide", "Émotions & pensées"],
    audience: ["child"],
    url: "https://primo.santepsyjeunes.fr/0",
    source: "Sante Psy Jeunes",
  },
  {
    id: "2ef1847b-1fab-4e2a-837e-1a123a6615ba",
    matomoId: 1,
    title: "Agenda du sommeil",
    description:
      "Cet agenda permet de suivre vos habitudes de sommeil au quotidien : heures de coucher, réveils, qualité du sommeil et comportements liés à la vigilance. Il aide à mieux comprendre vos rythmes et à identifier d’éventuels troubles du sommeil.",
    type: ["Fichier"],
    themes: ["Sommeil"],
    audience: ["child", "parent", "student"],
    url: "https://www.reseau-morphee.fr/wp-content/uploads/2009/01/agenda_2p.pdf",
    source: "Reseau Morphée",
  },
];
