# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require('dotenv')
Dotenv.load
# to get variables from .env files : ENV["MY_VAR_NAME"]

default_platform(:ios)

platform :ios do
  desc "Auto Increment BuildNumber"
  lane :IncrementBuildNumber do
    increment_build_number(xcodeproj: "ere360.xcodeproj")
  end

  desc "Set version number"
  lane :SetVersiondNameToMatchPackageJson do |options|
    if options[:version_name]
      # extract options to a variable
      version_name = options[:version_name]
      increment_version_number(
        version_number: version_name # Set a specific version number
      )
    end

  end

  desc "Push a new beta build to TestFlight localy"
  lane :testFlightLocal do
    build_app(workspace: "monsuivipsy.xcworkspace", scheme: "monsuivipsy")
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      api_key_path: './fastlane/appleApiKey.json'
    )
  end

  desc "Push a new beta build to TestFlight via github actions"
  lane :testFlightGithub do |options|
    if options[:certificate_password]
      # extract options to a variable
      certificate_password = options[:certificate_password]
    end

    create_keychain(
      name: 'ios_app_keychain',
      password: certificate_password,
      timeout: 1800,
      default_keychain: true,
      unlock: true,
      lock_when_sleeps: false
    )
    import_certificate(
      certificate_path: 'distribution.p12',
      certificate_password: certificate_password,
      keychain_name: 'ios_app_keychain',
      keychain_password: certificate_password
    )
    install_provisioning_profile(path: 'distribution.mobileprovision')
    update_project_provisioning(
      xcodeproj: 'monsuivipsy.xcodeproj',
      target_filter: 'github',
      profile: 'distribution.mobileprovision',
      build_configuration: 'Release'
    )

    build_app(workspace: "monsuivipsy.xcworkspace", scheme: "monsuivipsy")
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      api_key_path: './fastlane/appleApiKey.json'
    )
  end
end
