export const GOALS_ONBOARDING = [
  "Trouver 3 choses positives de la journée",
  "Je fais une activité plaisir",
  "Contact social",
  null,
  "Horaires réguliers de sommeil",
  "30 min d’activité physique",
  "Pas de grignotage entre les repas",
  null,
  "Me lever le matin",
  "Faire mes tâches ménagères",
  "Faire mes tâches administratives",
];

export const GOALS_EXAMPLE = {
  "Se faire plaisir": [
    "Je fais une activité plaisir",
    "Trouver 3 choses positives de la journée",
    "Je m’accorde une pause",
    "Me promener dehors",
    "J’aide quelqu’un",
    "Je fais un de mes hobbies",
    "Je soigne mon apparence",
    "J’ai pris mon temps pour manger",
    "Je pense à une chose positive",
    'Faire un achat "plaisir" pour soi',
  ],
  "Prendre soin de sa santé": [
    "Horaires réguliers de sommeil",
    "30 min d’activité physique",
    "J’ai cuisiné mes plats",
    "J'ai pris une pause au travail",
    "Manger 5 fruits et légumes",
    "Pas de grignotage entre les repas",
    "J’ai pris correctement mon traitement",
    "Faire ma cohérence cardiaque",
    "Je limite mon temps d’écran",
    "Je ne fume pas",
    "Je respecte mes limites",
    "Méditation",
  ],
  "Au quotidien": [
    "Faire mes tâches ménagères",
    "Me lever le matin",
    "Faire le bilan des choses que j’ai réalisées aujourd’hui",
    "Soigner son apparence",
    "J’ai fait mes courses",
    "S’occuper de son hygiène",
    "Faire mes tâches administratives",
    "J’ai réalisé un planning de ce que j’ai à faire",
    "Communication avec mes proches",
    "Contact social",
  ],
};
