import localStorage from "../utils/localStorage";

// export const getDrugListWithLocalStorage = async () => {
//   const customDrugs = await localStorage.getCustomDrugs();
//   const tempList = [...INDICATEURS_LISTE];
//   tempList.push(...customDrugs);
//   return tempList;
// };

export const INDICATEURS_HUMEUR = "Humeur générale";
export const INDICATEURS_SOMMEIL = "Qualité sommeil";

export const INDICATEURS_LISTE_ONBOARDING_HUMEUR = [
  "Humeur matinale",
  "Humeur à la mi-journée",
  "Humeur au coucher",
];
export const INDICATEURS_LISTE_ONBOARDING_SOMMEIL = [
  "Durée sommeil",
  "Facilité endormissement",
  // "Se coucher tôt",
  "Fatigue",
  "Réveils nocturnes",
];
export const INDICATEURS_LISTE_ONBOARDING_CUSTOM_SIMPLE = [
  "Anxiété",
  "Confiance",
  "Colère",
  "Idées noires",
  null,
  "Fatigue",
  "Crise de larmes",
  "Procrastination",
  "Ruminations sur le passé",
  null,
  "Je suis fier(e) de moi",
  "Je me sens seul(e)",
];

export const INDICATEURS_GOALS_SIMPLE = [
  "Trouver 3 choses positives de la journée",
  "Je fais une activité plaisir",
  "Contact social",
  null,
  "Horaires réguliers de sommeil",
  "30 min d’activité physique",
  null,
  "Me lever le matin",
  "Faire mes tâches ménagères",
  "Faire mes tâches administratives",
];

export const INDICATEURS_LISTE_ONBOARDING = [
  "Humeur générale",
  "Anxiété",
  "Colère",
  "Idées noires",
  "Je suis fier(e) de moi",
  "Confiance en soi",
  "Qualité sommeil",
  "Durée sommeil",
  "Je fais une activité plaisir",
  "Faire mes tâches ménagères",
];

export const INDICATEURS = {
  // Emotions/sentiments
  "Humeur générale": "Humeur générale",
  Anxiété: "Anxiété",
  Colère: "Colère",
  Angoisse: "Angoisse",
  "Confiance en soi": "Confiance en soi",
  "Idées noires": "Idées noires",
  Honte: "Honte",
  Motivation: "Motivation",
  Plaisir: "Plaisir",
  Energie: "Energie",
  Stress: "Stress",
  "Estime de soi": "Estime de soi",
  Irritabilité: "Irritabilité",
  Découragement: "Découragement",
  Euphorie: "Euphorie",
  Espoir: "Espoir",
  Tristesse: "Tristesse",
  Culpabilité: "Culpabilité",
  Optimisme: "Optimisme",
  Inquiétude: "Inquiétude",
  Libido: "Libido",
  "Idées suicidaires": "Idées suicidaires",
  "Humeur matinale": "Humeur matinale",
  "Humeur à la mi-journée": "Humeur à la mi-journée",
  "Humeur au coucher": "Humeur au coucher",
  //Manifestations physiques
  Fatigue: "Fatigue",
  "Mal au ventre": "Mal au ventre",
  Menstruations: "Menstruations",
  Appétit: "Appétit",
  Nausées: "Nausées",
  "Respiration rapide": "Respiration rapide",
  Tachycardie: "Tachycardie",
  Vertiges: "Vertiges",
  "Prise de poids": "Prise de poids",
  "Perte de poids": "Perte de poids",
  Douleur: "Douleur",
  "Maux de tête": "Maux de tête",
  Agitation: "Agitation",
  //Pensées
  "Je suis fier(e) de moi": "Je suis fier(e) de moi",
  "Je me sens bien": "Je me sens bien",
  "Je suis surmené(e)": "Je suis surmené(e)",
  "J’ai besoin de contrôler": "J’ai besoin de contrôler",
  "Je vais y arriver": "Je vais y arriver",
  "Je suis à l’aise dans mes relations sociales": "Je suis à l’aise dans mes relations sociales",
  "Tout le monde est contre moi": "Tout le monde est contre moi",
  "Je suis à la hauteur des (de mes) exigences": "Je suis à la hauteur des (de mes) exigences",
  "Je me sens harcelé(e)": "Je me sens harcelé(e)",
  "Je peux compter sur mon entourage": "Je peux compter sur mon entourage",
  "Je ne veux voir personne": "Je ne veux voir personne",
  "Je me sens seul(e)": "Je me sens seul(e)",
  "Je me sens jugé(e)/critiqué(e)": "Je me sens jugé(e)/critiqué(e)",
  //Comportements
  Procrastination: "Procrastination",
  "Je me projette dans l’avenir": "Je me projette dans l’avenir",
  "Crise de larmes": "Crise de larmes",
  "Ruminations sur le passé": "Ruminations sur le passé",
  "Auto-mutilation": "Auto-mutilation",
  "Je me compare aux autres": "Je me compare aux autres",
  "Consommation d’alcool": "Consommation d’alcool",
  "Crise de colère": "Crise de colère",
  "Crise de boulimie": "Crise de boulimie",
  "J’accepte l’aide que l’on m’apporte": "J’accepte l’aide que l’on m’apporte",
  "J’ai réussi à affronter une de mes angoisses": "J’ai réussi à affronter une de mes angoisses",
  "Comportement sexuel à risques": "Comportement sexuel à risques",
  "Je vais chercher du soutien": "Je vais chercher du soutien",
  Inhibition: "Inhibition",
  "J’exprime mes sentiments": "J’exprime mes sentiments",
  "J’exprime mes sentiments négatifs sans culpabilité": "J’exprime mes sentiments négatifs sans culpabilité",
  "Achats inhabituels": "Achats inhabituels",
  Désinhibition: "Désinhibition",
  //Se faire plaisir
  "Je fais une activité plaisir": "J'ai fait une activité plaisir",
  "Trouver 3 choses positives de la journée": "Trouver 3 choses positives de la journée",
  "Je m’accorde une pause": "Je m’accorde une pause",
  "Me promener dehors": "Me promener dehors",
  "J’aide quelqu’un": "J’aide quelqu’un",
  "Je fais un de mes hobbies": "Je fais un de mes hobbies",
  "Je soigne mon apparence": "Je soigne mon apparence",
  "Passer du temps avec ceux que j’apprécie": "Passer du temps avec ceux que j’apprécie",
  "Contact social": "Contact social",
  "J’ai pris mon temps pour manger": "J’ai pris mon temps pour manger",
  "Je pense à une chose positive": "Je pense à une chose positive",
  'Faire un achat "plaisir" pour soi': 'Faire un achat "plaisir" pour soi',
  //Prendre soin de sa santé
  "Qualité sommeil": "Qualité du sommeil",
  "Durée sommeil": "Durée du sommeil",
  "Facilité endormissement": "Facilité endormissement",
  "Se coucher tôt": "Me coucher tôt",
  "Réveils nocturnes": "Réveils nocturnes",
  "Horaires réguliers de sommeil": "Horaires réguliers de sommeil",
  "30 min d’activité physique": "30 min d’activité physique",
  "J’ai cuisiné mes plats": "J’ai cuisiné mes plats",
  "J'ai pris une pause au travail": "J'ai pris une pause au travail",
  "Manger 5 fruits et légumes": "Manger 5 fruits et légumes",
  "Grignotage entre les repas": "Grignotage entre les repas",
  "J’ai pris correctement mon traitement": "J’ai pris correctement mon traitement",
  "Faire ma cohérence cardiaque": "Faire ma cohérence cardiaque",
  "Je limite mon temps d’écran": "Je limite mon temps d’écran",
  "Je ne fume pas": "Je ne fume pas",
  "Je respecte mes limites": "Je respecte mes limites",
  Méditation: "Méditation",
  //Au quotidien
  "Faire mes tâches ménagères": "Faire mes tâches ménagères",
  "Me lever le matin": "Me lever le matin",
  "Faire le bilan des choses que j’ai réalisées aujourd’hui":
    "Faire le bilan des choses que j’ai réalisées aujourd’hui",
  "Soigner son apparence": "Soigner son apparence",
  "J’ai fait mes courses": "J’ai fait mes courses",
  "S’occuper de son hygiène": "S’occuper de son hygiène",
  "Se fixer des objectifs": "Se fixer des objectifs",
  "J'ai réalisé mes objectifs": "J'ai réalisé mes objectifs",
  "Faire mes tâches administratives": "Faire mes tâches administratives",
  "J’ai réalisé un planning de ce que j’ai à faire": "J’ai réalisé un planning de ce que j’ai à faire",
  "Communication avec mon entourage": "Communication avec mon entourage",
};

export const INDICATEURS_LISTE_PAR_CATEGORIE = {
  "Les plus courants": [
    "Humeur générale",
    "Humeur matinale",
    "Humeur à la mi-journée",
    "Humeur au coucher",
    "Qualité sommeil",
    "Durée sommeil",
    "Facilité endormissement",
    "Se coucher tôt",
    "Energie",
    "Anxiété",
    "Je suis fier(e) de moi",
    "Je fais une activité plaisir",
    "Faire mes tâches ménagères",
  ],
  "Emotions/sentiments": [
    "Humeur générale",
    "Anxiété",
    "Colère",
    "Angoisse",
    "Confiance en soi",
    "Idées noires",
    "Honte",
    "Motivation",
    "Plaisir",
    "Stress",
    "Estime de soi",
    "Irritabilité",
    "Découragement",
    "Euphorie",
    "Espoir",
    "Tristesse",
    "Culpabilité",
    "Optimisme",
    "Inquiétude",
    "Libido",
    "Idées suicidaires",
    "Humeur matinale",
    "Humeur à la mi-journée",
    "Humeur au coucher",
  ],
  "Manifestations physiques": [
    "Energie",
    "Mal au ventre",
    "Menstruations",
    "Appétit",
    "Nausées",
    "Respiration rapide",
    "Tachycardie",
    "Vertiges",
    "Prise de poids",
    "Perte de poids",
    "Douleur",
    "Maux de tête",
    "Agitation",
    "Qualité sommeil",
    "Durée sommeil",
    "Facilité endormissement",
    "Réveils nocturnes",
    "Fatigue",
  ],
  Pensées: [
    "Je suis fier(e) de moi",
    "Je me sens bien",
    "Je suis surmené(e)",
    "J’ai besoin de contrôler",
    "Je vais y arriver",
    "Je suis à l’aise dans mes relations sociales",
    "Tout le monde est contre moi",
    "Je suis à la hauteur des (de mes) exigences",
    "Je me sens harcelé(e)",
    "Je peux compter sur mon entourage",
    "Je ne veux voir personne",
    "Je me sens seul(e)",
    "Je me sens jugé(e)/critiqué(e)",
  ],
  Comportements: [
    "Procrastination",
    "Je me projette dans l’avenir",
    "Crise de larmes",
    "Ruminations sur le passé",
    "Auto-mutilation",
    "Je me compare aux autres",
    "Consommation d’alcool",
    "Crise de colère",
    "Crise de boulimie",
    "J’accepte l’aide que l’on m’apporte",
    "J’ai réussi à affronter une de mes angoisses",
    "Comportement sexuel à risques",
    "Je vais chercher du soutien",
    "Inhibition",
    "Grignotage entre les repas",
    "J’exprime mes sentiments",
    "J’exprime mes sentiments négatifs sans culpabilité",
    "Achats inhabituels",
    "Désinhibition",
  ],
  "Se faire plaisir": [
    "Je fais une activité plaisir",
    "Trouver 3 choses positives de la journée",
    "Je m’accorde une pause",
    "Me promener dehors",
    "J’aide quelqu’un",
    "Je fais un de mes hobbies",
    "Je soigne mon apparence",
    "Passer du temps avec ceux que j’apprécie",
    "Contact social",
    "J’ai pris mon temps pour manger",
    "Je pense à une chose positive",
    'Faire un achat "plaisir" pour soi',
  ],
  "Prendre soin de sa santé": [
    "Se coucher tôt",
    "Horaires réguliers de sommeil",
    "30 min d’activité physique",
    "J’ai cuisiné mes plats",
    "J'ai pris une pause au travail",
    "Manger 5 fruits et légumes",
    "Grignotage entre les repas",
    "J’ai pris correctement mon traitement",
    "Faire ma cohérence cardiaque",
    "Je limite mon temps d’écran",
    "Je ne fume pas",
    "Je respecte mes limites",
    "Méditation",
  ],
  "Au quotidien": [
    "Faire mes tâches ménagères",
    "Me lever le matin",
    "Faire le bilan des choses que j’ai réalisées aujourd’hui",
    "Soigner son apparence",
    "J’ai fait mes courses",
    "S’occuper de son hygiène",
    "Se fixer des objectifs",
    "J'ai réalisé mes objectifs",
    "Faire mes tâches administratives",
    "J’ai réalisé un planning de ce que j’ai à faire",
    "Communication avec mon entourage",
  ],
};

export const INDICATEURS_LISTE = Object.values(INDICATEURS_LISTE_PAR_CATEGORIE).reduce(
  (acc, curr) => [...acc, ...curr],
  []
);
