import { INDICATORS_CATEGORIES, PredefineIndicatorSchemaType } from "../entities/Indicator";

export const INDICATEURS_HUMEUR = {
  uuid: "3e15ed99-f2f9-4716-b6a2-5348c35266da",
  name: "Humeur générale",
  category: INDICATORS_CATEGORIES["Emotions/sentiments"],
  order: "ASC",
  type: "smiley",
};

export const INDICATEURS_SOMMEIL = {
  uuid: "d21db60d-ffa7-4063-a011-d7faef93bed2",
  name: "Qualité sommeil",
  category: INDICATORS_CATEGORIES["Manifestations physiques"],
  order: "ASC",
  type: "gauge",
};

export const INDICATEURS_LISTE_ONBOARDING_HUMEUR = [
  {
    uuid: "60f6eb32-698c-47c0-b99e-fb03a576b7c1",
    name: "Humeur matinale",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "51ead8a8-0f08-4527-98ce-e101cd7da50d",
    name: "Humeur à la mi-journée",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "e190182b-e2d3-4d09-bee6-21ba6baf0b25",
    name: "Humeur au coucher",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "ASC",
    type: "smiley",
  },
];

export const INDICATEURS_LISTE_ONBOARDING_SOMMEIL = [
  {
    uuid: "6fb2564a-c2ab-44ca-80d7-88473fe0e414",
    name: "Durée sommeil",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "b36556bb-5f13-4214-a05b-f31619115f5b",
    name: "Facilité endormissement",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "1c7d836a-2174-49a0-9b98-888b577dc212",
    name: "Fatigue",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "0eefce3d-7955-4eff-b6cc-7da2de12bdce",
    name: "Réveils nocturnes",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "DESC",
    type: "boolean",
  },
];

export const INDICATEURS: PredefineIndicatorSchemaType[] = [
  // Emotions/sentiments
  {
    uuid: "3e15ed99-f2f9-4716-b6a2-5348c35266da",
    name: "Humeur générale",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "cde300cd-aecd-4821-b21b-73db4cfa6354",
    name: "Anxiété",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "f2cdd835-fb9c-453f-a6ca-cf85d731bb4f",
    name: "Colère",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "63da973c-0d68-4b23-993b-592d9ae46cec",
    name: "Angoisse",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "49cf6796-e1b3-4878-875b-5851e8a58b5f",
    name: "Confiance en soi",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "ae48397d-f491-46d4-923f-7d553aed225d",
    name: "Idées noires",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "d238c797-7892-4c47-867c-2367bd56df41",
    name: "Honte",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "bbaca8c5-cdb8-4186-8577-bdcd1fc9a21b",
    name: "Motivation",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "aefc0440-df88-4430-9e74-756933539dbe",
    name: "Plaisir",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "4d5b67c3-6919-4033-8374-c8f089b54cb8",
    name: "Stress",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "6872adcb-3e40-4d47-8b86-8b5edb024103",
    name: "Estime de soi",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "201c2ae8-41aa-4b6a-b68a-6c9dcd14afdf",
    name: "Irritabilité",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "a5190e1c-b780-423c-a86c-9c046a96d8bf",
    name: "Découragement",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "a24642d0-7984-4e63-a1a6-d13a83aa7643",
    name: "Euphorie",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "b009976f-30b4-40be-8c71-dbcc6c975739",
    name: "Espoir",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "a9eab5ae-f76a-4729-ab65-6fe76dc29933",
    name: "Tristesse",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "9e2d7768-8282-402a-a7b7-7ababdeaa65c",
    name: "Culpabilité",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "1a879ba5-1fbe-41e5-9df7-532aa7ea0d53",
    name: "Optimisme",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "661dfd08-ba45-450b-a115-c7380c17ed88",
    name: "Inquiétude",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "6a092397-927d-464b-b6ef-ed1da357ab62",
    name: "Libido",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "137a047f-7831-4109-9052-fc757be8986f",
    name: "Idées suicidaires",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "60f6eb32-698c-47c0-b99e-fb03a576b7c1",
    name: "Humeur matinale",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "51ead8a8-0f08-4527-98ce-e101cd7da50d",
    name: "Humeur à la mi-journée",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "e190182b-e2d3-4d09-bee6-21ba6baf0b25",
    name: "Humeur au coucher",
    category: INDICATORS_CATEGORIES["Emotions/sentiments"],
    order: "ASC",
    type: "smiley",
  },
  // Manifestations physiques
  {
    uuid: "1c7d836a-2174-49a0-9b98-888b577dc212",
    name: "Fatigue",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "3167251f-40bb-4b81-b0a0-97ebf766fb15",
    name: "Mal au ventre",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "dd1df4f8-6b11-4833-a24d-d0f7c63af9b1",
    name: "Menstruations",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "c6099cd3-2b10-46d8-930e-f08ed97b2505",
    name: "Appétit",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "53e79654-b750-4b79-a589-37f1b880053c",
    name: "Nausées",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "64909dde-bcdf-4a5c-879c-edbe14779a5a",
    name: "Respiration rapide",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "232210d8-59c7-47ac-a817-c6fef13d1384",
    name: "Tachycardie",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "76093def-7576-41be-9f65-b892b734bc45",
    name: "Vertiges",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "9d908fa4-a37a-4bf7-bebd-931909dace3f",
    name: "Prise de poids",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "d7078d7a-c057-4802-9f7a-6d514e6b442d",
    name: "Perte de poids",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "17143032-5bad-4407-ac5c-0ab676346389",
    name: "Douleur",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "8553e6a1-5916-492d-ac05-0b2009a1a9c8",
    name: "Maux de tête",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "4ae01a3d-ed57-4fe7-963b-6bda2382f5b4",
    name: "Agitation",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "d21db60d-ffa7-4063-a011-d7faef93bed2",
    name: "Qualité sommeil",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "6fb2564a-c2ab-44ca-80d7-88473fe0e414",
    name: "Durée sommeil",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "b36556bb-5f13-4214-a05b-f31619115f5b",
    name: "Facilité endormissement",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "0eefce3d-7955-4eff-b6cc-7da2de12bdce",
    name: "Réveils nocturnes",
    category: INDICATORS_CATEGORIES["Manifestations physiques"],
    order: "DESC",
    type: "boolean",
  },
  // Pensées
  {
    uuid: "eac70ab8-ee01-4ffd-8627-7903c3a861c0",
    name: "Je suis fier(e) de moi",
    category: INDICATORS_CATEGORIES["Pensées"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "8137e2af-b5c8-4d62-a3ab-09a6f8eb5d77",
    name: "Je me sens bien",
    category: INDICATORS_CATEGORIES["Pensées"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "d6612c20-e68c-4092-918b-80a9fff3d145",
    name: "Je suis surmené(e)",
    category: INDICATORS_CATEGORIES["Pensées"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "4861a112-9f2c-4768-9ed7-184ee6f171a4",
    name: "J’ai besoin de contrôler",
    category: INDICATORS_CATEGORIES["Pensées"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "2c7b000b-a77a-4ec5-ac27-8b862d41d080",
    name: "Je vais y arriver",
    category: INDICATORS_CATEGORIES["Pensées"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "4ac12fd1-0481-4307-a52a-08255dd4cdf9",
    name: "Je suis à l’aise dans mes relations sociales",
    category: INDICATORS_CATEGORIES["Pensées"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "89728100-8951-4342-8858-feccc7d40c2f",
    name: "Tout le monde est contre moi",
    category: INDICATORS_CATEGORIES["Pensées"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "b889625c-b563-4b05-9871-df2dbd9a4f5d",
    name: "Je suis à la hauteur des (de mes) exigences",
    category: INDICATORS_CATEGORIES["Pensées"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "489084b0-ca41-4c9b-b0d7-078b886b7d4d",
    name: "Je me sens harcelé(e)",
    category: INDICATORS_CATEGORIES["Pensées"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "e2d51f8e-a84a-4557-a4a1-e8a64205841d",
    name: "Je peux compter sur mon entourage",
    category: INDICATORS_CATEGORIES["Pensées"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "be13c0cc-b4c0-4f3e-8771-8fb8eebe6290",
    name: "Je ne veux voir personne",
    category: INDICATORS_CATEGORIES["Pensées"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "6058c367-e5c6-4f08-ae8b-e6032b4c94af",
    name: "Je me sens seul(e)",
    category: INDICATORS_CATEGORIES["Pensées"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "633ef9c1-0ad8-4c1f-9db0-bef3074af28b",
    name: "Je me sens jugé(e)/critiqué(e)",
    category: INDICATORS_CATEGORIES["Pensées"],
    order: "DESC",
    type: "gauge",
  },
  // Comportements
  {
    uuid: "70b93828-1a42-4887-a000-87754a4bcca7",
    name: "Procrastination",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "e4ea6334-8ab4-4a53-be32-0434df7e853a",
    name: "Je me projette dans l’avenir",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "ASC",
    type: "gauge",
  },
  {
    uuid: "5cfc6e92-1f98-487d-a8a7-6af0c4b1c84f",
    name: "Crise de larmes",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "0d277137-afb5-4926-a81c-3d278139f764",
    name: "Ruminations sur le passé",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "4a8789f1-be94-45d9-9fec-37df8c49df95",
    name: "Auto-mutilation",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "a4abae14-93ef-4f8e-b634-903507303c47",
    name: "Je me compare aux autres",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "6abafbf9-6467-42e0-a4f1-61be13fd9166",
    name: "Consommation d’alcool",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "0bab23bc-eca7-4688-966b-f1d8e93f48d4",
    name: "Crise de colère",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "e5137f70-8e94-4009-b2ec-ee86516e32e8",
    name: "Crise de boulimie",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "f626731d-37db-42a8-9121-b781deb54d94",
    name: "TOC",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "effe9ec3-718b-4ed4-9f5a-7743ac4b9f37",
    name: "J’accepte l’aide que l’on m’apporte",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "ASC",
    type: "boolean",
  },
  {
    uuid: "aec15a2d-384f-47fb-b4a8-1045825ad7a6",
    name: "J’ai réussi à affronter une de mes angoisses",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "ASC",
    type: "boolean",
  },
  {
    uuid: "87850ec4-5a6d-4530-af7a-a64c7f6fcfdd",
    name: "Comportement sexuel à risques",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "173c7f41-27d8-4bf2-bb5a-6bbfef5cdb78",
    name: "Je vais chercher du soutien",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "ASC",
    type: "boolean",
  },
  {
    uuid: "be9d1193-68e1-494d-b069-91302767259f",
    name: "Grignotage entre les repas",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "2a1dafa6-9d88-4639-a044-df87f7d51cdb",
    name: "J’exprime mes sentiments",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "ASC",
    type: "boolean",
  },
  {
    uuid: "2ce8aeec-527f-477e-9c49-1c5502b2df24",
    name: "J’exprime mes sentiments négatifs sans culpabilité",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "ASC",
    type: "boolean",
  },
  {
    uuid: "8231bc02-84df-489b-9756-d62e2ed0e5ab",
    name: "Achats inhabituels",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "DESC",
    type: "boolean",
  },
  {
    uuid: "933ae75d-8271-4e30-9107-232310bae4b7",
    name: "Inhibition",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "DESC",
    type: "gauge",
  },
  {
    uuid: "1a4ce5e5-82ea-46cb-8cac-737ffd9a610b",
    name: "Désinhibition",
    category: INDICATORS_CATEGORIES["Comportements"],
    order: "DESC",
    type: "gauge",
  },
];

export const INDICATEURS_LIST = {
  // Emotions/sentiments
  "Humeur générale": "Humeur générale",
  Anxiété: "Anxiété",
  Colère: "Colère",
  Angoisse: "Angoisse",
  "Confiance en soi": "Confiance en soi",
  "Idées noires": "Idées noires",
  Honte: "Honte",
  Motivation: "Motivation",
  Plaisir: "Plaisir",
  Energie: "Energie",
  Stress: "Stress",
  "Estime de soi": "Estime de soi",
  Irritabilité: "Irritabilité",
  Découragement: "Découragement",
  Euphorie: "Euphorie",
  Espoir: "Espoir",
  Tristesse: "Tristesse",
  Culpabilité: "Culpabilité",
  Optimisme: "Optimisme",
  Inquiétude: "Inquiétude",
  Libido: "Libido",
  "Idées suicidaires": "Idées suicidaires",
  "Humeur matinale": "Humeur matinale",
  "Humeur à la mi-journée": "Humeur à la mi-journée",
  "Humeur au coucher": "Humeur au coucher",
  //Manifestations physiques
  Fatigue: "Fatigue",
  "Mal au ventre": "Mal au ventre",
  Menstruations: "Menstruations",
  Appétit: "Appétit",
  Nausées: "Nausées",
  "Respiration rapide": "Respiration rapide",
  Tachycardie: "Tachycardie",
  Vertiges: "Vertiges",
  "Prise de poids": "Prise de poids",
  "Perte de poids": "Perte de poids",
  Douleur: "Douleur",
  "Maux de tête": "Maux de tête",
  Agitation: "Agitation",
  //Pensées
  "Je suis fier(e) de moi": "Je suis fier(e) de moi",
  "Je me sens bien": "Je me sens bien",
  "Je suis surmené(e)": "Je suis surmené(e)",
  "J’ai besoin de contrôler": "J’ai besoin de contrôler",
  "Je vais y arriver": "Je vais y arriver",
  "Je suis à l’aise dans mes relations sociales": "Je suis à l’aise dans mes relations sociales",
  "Tout le monde est contre moi": "Tout le monde est contre moi",
  "Je suis à la hauteur des (de mes) exigences": "Je suis à la hauteur des (de mes) exigences",
  "Je me sens harcelé(e)": "Je me sens harcelé(e)",
  "Je peux compter sur mon entourage": "Je peux compter sur mon entourage",
  "Je ne veux voir personne": "Je ne veux voir personne",
  "Je me sens seul(e)": "Je me sens seul(e)",
  "Je me sens jugé(e)/critiqué(e)": "Je me sens jugé(e)/critiqué(e)",
  //Comportements
  Procrastination: "Procrastination",
  "Je me projette dans l’avenir": "Je me projette dans l’avenir",
  "Crise de larmes": "Crise de larmes",
  "Ruminations sur le passé": "Ruminations sur le passé",
  "Auto-mutilation": "Auto-mutilation",
  "Je me compare aux autres": "Je me compare aux autres",
  "Consommation d’alcool": "Consommation d’alcool",
  "Crise de colère": "Crise de colère",
  "Crise de boulimie": "Crise de boulimie",
  "J’accepte l’aide que l’on m’apporte": "J’accepte l’aide que l’on m’apporte",
  "J’ai réussi à affronter une de mes angoisses": "J’ai réussi à affronter une de mes angoisses",
  "Comportement sexuel à risques": "Comportement sexuel à risques",
  "Je vais chercher du soutien": "Je vais chercher du soutien",
  Inhibition: "Inhibition",
  "J’exprime mes sentiments": "J’exprime mes sentiments",
  "J’exprime mes sentiments négatifs sans culpabilité": "J’exprime mes sentiments négatifs sans culpabilité",
  "Achats inhabituels": "Achats inhabituels",
  Désinhibition: "Désinhibition",
};

export const INDICATEURS_LES_PLUS_COURANTS = INDICATEURS.filter((indicateur) =>
  [
    "3e15ed99-f2f9-4716-b6a2-5348c35266da",
    "60f6eb32-698c-47c0-b99e-fb03a576b7c1",
    "51ead8a8-0f08-4527-98ce-e101cd7da50d",
    "e190182b-e2d3-4d09-bee6-21ba6baf0b25",
    "d21db60d-ffa7-4063-a011-d7faef93bed2",
    "6fb2564a-c2ab-44ca-80d7-88473fe0e414",
    "b36556bb-5f13-4214-a05b-f31619115f5b",
    "07ff691d-09b1-4ec9-8902-8dae02521f3d",
    "d019eb7c-6552-4e9b-97b9-6aac86c1d8bc",
    "cde300cd-aecd-4821-b21b-73db4cfa6354",
    "eac70ab8-ee01-4ffd-8627-7903c3a861c0",
    "0e1467c1-e422-4383-a9b4-d4179457cc8b",
    "43688363-b5aa-4f44-ac78-56b43eb72923",
  ].includes(indicateur.uuid)
);

export const INDICATEURS_LISTE_ONBOARDING_CUSTOM_SIMPLE = [
  INDICATEURS.filter((indicateur) =>
    [
      "cde300cd-aecd-4821-b21b-73db4cfa6354",
      "49cf6796-e1b3-4878-875b-5851e8a58b5f",
      "f2cdd835-fb9c-453f-a6ca-cf85d731bb4f",
      "ae48397d-f491-46d4-923f-7d553aed225d",
    ].includes(indicateur.uuid)
  ),
  INDICATEURS.filter((indicateur) =>
    [
      "1c7d836a-2174-49a0-9b98-888b577dc212",
      "5cfc6e92-1f98-487d-a8a7-6af0c4b1c84f",
      "70b93828-1a42-4887-a000-87754a4bcca7",
      "0d277137-afb5-4926-a81c-3d278139f764",
    ].includes(indicateur.uuid)
  ),
  INDICATEURS.filter((indicateur) =>
    ["eac70ab8-ee01-4ffd-8627-7903c3a861c0", "6058c367-e5c6-4f08-ae8b-e6032b4c94af"].includes(indicateur.uuid)
  ),
];

export const INDICATEURS_LISTE_PAR_CATEGORIE = {
  "Les plus courants": [
    "Humeur générale",
    "Humeur matinale",
    "Humeur à la mi-journée",
    "Humeur au coucher",
    "Qualité sommeil",
    "Durée sommeil",
    "Facilité endormissement",
    "Se coucher tôt",
    "Energie",
    "Anxiété",
    "Je suis fier(e) de moi",
    "Je fais une activité plaisir",
    "Faire mes tâches ménagères",
  ],
  "Emotions/sentiments": [
    "Humeur générale",
    "Anxiété",
    "Colère",
    "Angoisse",
    "Confiance en soi",
    "Idées noires",
    "Honte",
    "Motivation",
    "Plaisir",
    "Stress",
    "Estime de soi",
    "Irritabilité",
    "Découragement",
    "Euphorie",
    "Espoir",
    "Tristesse",
    "Culpabilité",
    "Optimisme",
    "Inquiétude",
    "Libido",
    "Idées suicidaires",
    "Humeur matinale",
    "Humeur à la mi-journée",
    "Humeur au coucher",
  ],
  "Manifestations physiques": [
    "Energie",
    "Mal au ventre",
    "Menstruations",
    "Appétit",
    "Nausées",
    "Respiration rapide",
    "Tachycardie",
    "Vertiges",
    "Prise de poids",
    "Perte de poids",
    "Douleur",
    "Maux de tête",
    "Agitation",
    "Qualité sommeil",
    "Durée sommeil",
    "Facilité endormissement",
    "Réveils nocturnes",
    "Fatigue",
  ],
  Pensées: [
    "Je suis fier(e) de moi",
    "Je me sens bien",
    "Je suis surmené(e)",
    "J’ai besoin de contrôler",
    "Je vais y arriver",
    "Je suis à l’aise dans mes relations sociales",
    "Tout le monde est contre moi",
    "Je suis à la hauteur des (de mes) exigences",
    "Je me sens harcelé(e)",
    "Je peux compter sur mon entourage",
    "Je ne veux voir personne",
    "Je me sens seul(e)",
    "Je me sens jugé(e)/critiqué(e)",
  ],
  Comportements: [
    "Procrastination",
    "Je me projette dans l’avenir",
    "Crise de larmes",
    "Ruminations sur le passé",
    "Auto-mutilation",
    "Je me compare aux autres",
    "Consommation d’alcool",
    "Crise de colère",
    "Crise de boulimie",
    "J’accepte l’aide que l’on m’apporte",
    "J’ai réussi à affronter une de mes angoisses",
    "Comportement sexuel à risques",
    "Je vais chercher du soutien",
    "Inhibition",
    "Grignotage entre les repas",
    "J’exprime mes sentiments",
    "J’exprime mes sentiments négatifs sans culpabilité",
    "Achats inhabituels",
    "Désinhibition",
  ],
};

export const INDICATEURS_LISTE_ONBOARDING = [
  "Humeur générale",
  "Anxiété",
  "Colère",
  "Idées noires",
  "Je suis fier(e) de moi",
  "Confiance en soi",
  "Qualité sommeil",
  "Durée sommeil",
  "Je fais une activité plaisir",
  "Faire mes tâches ménagères",
];

export const INDICATEURS_LISTE = Object.values(INDICATEURS_LISTE_PAR_CATEGORIE).reduce(
  (acc, curr) => [...acc, ...curr],
  []
);

export const OLD_INDICATEURS_HUMEUR = "Humeur générale";
export const OLD_INDICATEURS_SOMMEIL = "Qualité sommeil";

export const OLD_INDICATEURS_LISTE_ONBOARDING_HUMEUR = [
  "Humeur matinale",
  "Humeur à la mi-journée",
  "Humeur au coucher",
];
export const OLD_INDICATEURS_LISTE_ONBOARDING_SOMMEIL = [
  "Durée sommeil",
  "Facilité endormissement",
  // "Se coucher tôt",
  "Fatigue",
  "Réveils nocturnes",
];

export const INDICATEURS_LISTE_ONBOARDING_CUSTOM_SIMPLE_LIST = [
  "Anxiété",
  "Confiance",
  "Colère",
  "Idées noires",
  null,
  "Fatigue",
  "Crise de larmes",
  "Procrastination",
  "Ruminations sur le passé",
  null,
  "Je suis fier(e) de moi",
  "Je me sens seul(e)",
];

