export const INDICATEURS = [
  // Emotions/sentiments
  {
    uuid: "f516848a-3b21-4ac3-99f6-c3ec87b4e619",
    name: "Humeur générale",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "30a2bb25-ddbc-4690-af40-772ea410563d",
    name: "Anxiété",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "87dd780b-6a2a-4d30-ad81-99bcfb9b7988",
    name: "Colère",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "67862bf9-f225-40d2-81b9-e7fcd76e50f2",
    name: "Angoisse",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "6944ebac-5fb2-461c-a577-1ba50cc29572",
    name: "Confiance en soi",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "3705d210-7233-4fcd-8696-1d3a5e9992f9",
    name: "Idées noires",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Honte",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Motivation",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Plaisir",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Stress",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Estime de soi",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Irritabilité",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Découragement",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Euphorie",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Espoir",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Tristesse",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Culpabilité",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Optimisme",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Inquiétude",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Libido",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Idées suicidaires",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Humeur matinale",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Humeur à la mi-journée",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Humeur au coucher",
    category: "Emotions/sentiments",
    order: "ASC",
    type: "smiley",
  },
  // Manifestations physiques
  {
    uuid: "",
    name: "Energie",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Mal au ventre",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Menstruations",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Appétit",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Nausées",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Respiration rapide",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Tachycardie",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Vertiges",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Prise de poids",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Perte de poids",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Douleur",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Maux de tête",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Agitation",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Qualité sommeil",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Durée sommeil",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Facilité endormissement",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Réveils nocturnes",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Fatigue",
    category: "Manifestations physiques",
    order: "ASC",
    type: "smiley",
  },
  // Pensées
  {
    uuid: "",
    name: "Je suis fier(e) de moi",
    category: "Pensées",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je me sens bien",
    category: "Pensées",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je suis surmené(e)",
    category: "Pensées",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "J’ai besoin de contrôler",
    category: "Pensées",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je vais y arriver",
    category: "Pensées",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je suis à l’aise dans mes relations sociales",
    category: "Pensées",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Tout le monde est contre moi",
    category: "Pensées",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je suis à la hauteur des (de mes) exigences",
    category: "Pensées",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je me sens harcelé(e)",
    category: "Pensées",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je peux compter sur mon entourage",
    category: "Pensées",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je ne veux voir personne",
    category: "Pensées",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je me sens seul(e)",
    category: "Pensées",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je me sens jugé(e)/critiqué(e)",
    category: "Pensées",
    order: "ASC",
    type: "smiley",
  },
  // Comportements
  {
    uuid: "",
    name: "Procrastination",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je me projette dans l’avenir",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Crise de larmes",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Ruminations sur le passé",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Auto-mutilation",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je me compare aux autres",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Consommation d’alcool",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Crise de colère",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Crise de boulimie",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "J’accepte l’aide que l’on m’apporte",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "J’ai réussi à affronter une de mes angoisses",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Comportement sexuel à risques",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je vais chercher du soutien",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Inhibition",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Grignotage entre les repas",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "J’exprime mes sentiments",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "J’exprime mes sentiments négatifs sans culpabilité",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Achats inhabituels",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Désinhibition",
    category: "Comportements",
    order: "ASC",
    type: "smiley",
  },
  // Se faire plaisir
  {
    uuid: "",
    name: "Je fais une activité plaisir",
    category: "Se faire plaisir",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Trouver 3 choses positives de la journée",
    category: "Se faire plaisir",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je m’accorde une pause",
    category: "Se faire plaisir",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Me promener dehors",
    category: "Se faire plaisir",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "J’aide quelqu’un",
    category: "Se faire plaisir",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je fais un de mes hobbies",
    category: "Se faire plaisir",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je soigne mon apparence",
    category: "Se faire plaisir",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Passer du temps avec ceux que j’apprécie",
    category: "Se faire plaisir",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Contact social",
    category: "Se faire plaisir",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "J’ai pris mon temps pour manger",
    category: "Se faire plaisir",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je pense à une chose positive",
    category: "Se faire plaisir",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: 'Faire un achat "plaisir" pour soi',
    category: "Se faire plaisir",
    order: "ASC",
    type: "smiley",
  },
  // Prendre soin de sa santé
  {
    uuid: "",
    name: "Se coucher tôt",
    category: "Prendre soin de sa santé",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Horaires réguliers de sommeil",
    category: "Prendre soin de sa santé",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "30 min d’activité physique",
    category: "Prendre soin de sa santé",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "J’ai cuisiné mes plats",
    category: "Prendre soin de sa santé",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "J'ai pris une pause au travail",
    category: "Prendre soin de sa santé",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Manger 5 fruits et légumes",
    category: "Prendre soin de sa santé",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Grignotage entre les repas",
    category: "Prendre soin de sa santé",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "J’ai pris correctement mon traitement",
    category: "Prendre soin de sa santé",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Faire ma cohérence cardiaque",
    category: "Prendre soin de sa santé",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je limite mon temps d’écran",
    category: "Prendre soin de sa santé",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je ne fume pas",
    category: "Prendre soin de sa santé",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Je respecte mes limites",
    category: "Prendre soin de sa santé",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Méditation",
    category: "Prendre soin de sa santé",
    order: "ASC",
    type: "smiley",
  },
  // Au quotidien
  {
    uuid: "",
    name: "Faire mes tâches ménagères",
    category: "Au quotidien",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Me lever le matin",
    category: "Au quotidien",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Faire le bilan des choses que j’ai réalisées aujourd’hui",
    category: "Au quotidien",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Soigner son apparence",
    category: "Au quotidien",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "J’ai fait mes courses",
    category: "Au quotidien",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "S’occuper de son hygiène",
    category: "Au quotidien",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Se fixer des objectifs",
    category: "Au quotidien",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "J'ai réalisé mes objectifs",
    category: "Au quotidien",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Faire mes tâches administratives",
    category: "Au quotidien",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "J’ai réalisé un planning de ce que j’ai à faire",
    category: "Au quotidien",
    order: "ASC",
    type: "smiley",
  },
  {
    uuid: "",
    name: "Communication avec mon entourage",
    category: "Au quotidien",
    order: "ASC",
    type: "smiley",
  },
];
