app:
  ~chart: app
  probesPath: "/healthz"
  ~needs: [pg]
  containerPort: 3000
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: api

app-redirects:
  ~chart: app
  containerPort: 8080
  host: "app-{{ .Values.global.host }}"

pg:
  ~chart: pg
