app:
  probesPath: "/healthz"
  containerPort: 3000
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: api
jobs:
  runs:
    build-app:
      with:
        context: api
