FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source files
COPY src ./src
# COPY prisma ./prisma

# Generate Prisma client
# RUN npx prisma generate

# Set the entry point
CMD ["node", "src/reminderCronJobRunner.js"] 
